### ISSUE TITLE
APIError(code=-1013): Invalid price.

### ISSUE THREAD

**Issue by littleduckcoding** [ccxt/binance-trade-bot#10]
Hello,
I encountered an issue when attempting to order a limit buy. Specifically, I assigned order_price = get_market_ticker_price(client, alt_symbol+crypto_symbol) * 1.005 then rounded decimal places using math.floor(order_price * floor(10 ** ticks[alt_symbol])) / floor(10 ** ticks[alt_symbol]).

Eventually, I got "APIError(code=-1013): Invalid price" error. How to resolve this?

**Comment by edeng23** [comment]
Hey, not quite sure what you mean...
Are you making changes to the code?
