### ISSUE TITLE
Using docker, I get a "not a directory" error

### ISSUE THREAD

**Issue by leon1995** [ccxt/binance-trade-bot#102]
Hi,

when executing the script using python it works fine.
The docker version however returns an error:
```
ERROR: for binance_trader  Cannot start service crypto-trading: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "path/to/binance-trade-bot/.current_coin_table" to rootfs at "/var/lib/docker/overlay2/0c1f491c16541b52186a002a88e75cc95e9e202bfc644077b78667b0fc288379/merged/app/.current_coin_table" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

How can I resolve this, because I really want to use docker here :)

**Comment by Nico385412** [comment]
I've got the exact same error.
I noticed docker-compose created `.current_coin_table` as a directory.

A workaround : 
`rm -rf .current_coin && rm -rf .current_coin_table`
`echo 'BTC' > .current_coin && echo '{}' > .current_coin_table`

it should start the project 😁

**Comment by leon1995** [comment]
This doesn't work for me. I still get the same error

**Comment by quantumsheep** [comment]
Docker volumes should be directories, not files. #99 would fix the issue by setting a custom directory name.

**Comment by leon1995** [comment]
First, I let the script run to create the files. Then I rebuild the docker image using `docker-compose build`.
Now, `docker-compose up` works fine

**Comment by igorlemeshev** [comment]
> I've got the exact same error.
> I noticed docker-compose created `.current_coin_table` as a directory.
> 
> A workaround :
> `rm -rf .current_coin && rm -rf .current_coin_table`
> `echo 'BTC' > .current_coin && echo '{}' > .current_coin_table`
> 
> it should start the project 😁

Thanks, it helped. These were directories for me also
