### ISSUE TITLE
Sequence of errors

### ISSUE THREAD

**Issue by ayansengupta17** [ccxt/binance-trade-bot#108]
The script was working normally for a few hours and then, I started facing errors while scouting, but I did let it run to see what other errors I face, or if it gets resolved after a certain period of time. I think many users have faced one or the other error at some point.  

PS: The same error continues until a new error is thrown.

**02:04**
1. 2021-02-21 02:04:12,134 - crypto_trader_logger - INFO - Error while scouting...
('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**04:34**
2. 2021-02-21 04:34:58,983 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

**04:35**
3. 2021-02-21 04:35:34,029 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10f50fd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**04:53**
4. 2021-02-21 04:53:31,105 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10f50fa60>, 'Connection to api.binance.com timed out. (connect timeout=10)'))

**5:36**
5. 2021-02-21 05:36:02,301 - crypto_trader_logger - INFO - Error while scouting...
('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**07:32**

Found a suitable jump and proceeded accordingly.

**Comment by remriel** [comment]
I get this when my internet connection drops out in the middle of the night. If your internet connection isn't stable, it will give connection errors.

**Comment by edeng23** [comment]
Pretty sure this is because of internet connection problems. Did these errors affect the bot's ability to make trades afterwards?

**Comment by ayansengupta17** [comment]
> Pretty sure this is because of internet connection problems. Did these errors affect the bot's ability to make trades afterwards?

Apparently no, It was working fine after that! But My net connection couldn't have been out for so many hours! But I will definitely look into it. Thanks
