### ISSUE TITLE
Command ERRORED

### ISSUE THREAD

**Issue by mathius1714** [ccxt/binance-trade-bot#110]
Hello, I recieved this error trying to install pip. Any solution? Thanks

ERROR: Command errored out with exit status 1: 'c:\users\fènix vii\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Fènix VII\\AppData\\Local\\Temp\\pip-install-gnd91ojn\\twisted_3a231d2babe24895adb08ca038067d0c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Fènix VII\\AppData\\Local\\Temp\\pip-install-gnd91ojn\\twisted_3a231d2babe24895adb08ca038067d0c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Fènix VII\AppData\Local\Temp\pip-record-c4mmhhyr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fènix vii\appdata\local\programs\python\python39\Include\Twisted' Check the logs for full command output.

**Comment by ayansengupta17** [comment]
Not in the scope.

**Comment by mathius1714** [comment]
> Not in the scope.

So... Nothing to fix? :(

**Comment by salamzadeh** [comment]
> Hello, I recieved this error trying to install pip. Any solution? Thanks
> 
> ERROR: Command errored out with exit status 1: 'c:\users\fènix vii\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Fènix VII\AppData\Local\Temp\pip-install-gnd91ojn\twisted_3a231d2babe24895adb08ca038067d0c\setup.py'"'"'; **file**='"'"'C:\Users\Fènix VII\AppData\Local\Temp\pip-install-gnd91ojn\twisted_3a231d2babe24895adb08ca038067d0c\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Fènix VII\AppData\Local\Temp\pip-record-c4mmhhyr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fènix vii\appdata\local\programs\python\python39\Include\Twisted' Check the logs for full command output.

hi dear,
Are you using a Windows startup file?
pip is installed with python itself, what do you mean by trying install pip?

**Comment by mathius1714** [comment]
> > Hello, I recieved this error trying to install pip. Any solution? Thanks
> > ERROR: Command errored out with exit status 1: 'c:\users\fènix vii\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Fènix VII\AppData\Local\Temp\pip-install-gnd91ojn\twisted_3a231d2babe24895adb08ca038067d0c\setup.py'"'"'; **file**='"'"'C:\Users\Fènix VII\AppData\Local\Temp\pip-install-gnd91ojn\twisted_3a231d2babe24895adb08ca038067d0c\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Fènix VII\AppData\Local\Temp\pip-record-c4mmhhyr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\fènix vii\appdata\local\programs\python\python39\Include\Twisted' Check the logs for full command output.
> 
> hi dear,
> Are you using a Windows startup file?
> pip is installed with python itself, what do you mean by trying install pip?

Yes you are right, pip is installed with phyton itself, I'm so noobie sorry... I don't understand what's the problem... Do you know wich one could be? Thanks!

**Comment by nanashj** [comment]
‫أُرسلت من الـ iPhone‬

**Comment by edeng23** [comment]
I'm not sure what you're trying to do. Please elaborate.

**Comment by mathius1714** [comment]
> I'm not sure what you're trying to do. Please elaborate.

Hi. I just run the following line in the terminal: pip install -r requirements.txt. And this command give me the ERROR

**Comment by mathius1714** [comment]
Ok, I already fix it. Now after create .ini file with API sets and start the command:. /crypto_trading.py, a cmd window appears 1 second and desappears, and nothing happens... What's the problem? Thanks!

**Comment by rel-s** [comment]
Hi @mathius1714, we have a wonderful community on Discord that would gladly help you out with these problems. This is not a bug in the bot, and therefore this is not the right forum to hold this discussion. Please join our Discord, link in README.
