### ISSUE TITLE
Switch to Websocket API

### ISSUE THREAD

**Issue by rel-s** [ccxt/binance-trade-bot#118]
To allow a higher api request volume, we should use Binance's websocket APIs instead of the current implementation.

**Comment by luponata** [comment]
If i understand correctly (new repo user), we (should) or already use websockets to receive tickers, balance updates, orders updates... and API calls to make or cancel them.

ATM as far as i know, binance doesn't have a roadmap to allow making orders with websockets

https://dev.binance.vision/t/sending-and-canceling-orders-from-websocket-connection/437
https://www.binance.com/en/support/announcement/360035944992

Were there any developments unknown to me?

**Comment by jshield** [comment]
yeah so you can't place them, but you can pretty much subscribe to streams for everything else.
