### ISSUE TITLE
Graceful exit by pressing a key 

### ISSUE THREAD

**Issue by ch3ckmat3** [ccxt/binance-trade-bot#126]
For example, pressing 'Q' will show console message that the bot is preparing to exit, and then closes current operation and leaves the system in a [proper state for the next run.

Pressing Ctrl-C to kill the loop sometimes leave the system in a state that you must manually reset things in DB, Config and Binance account to make the system workable again.

**Comment by rel-s** [comment]
I think a more generic approach needs to be taken to fix this issue - we are currently working on implementing APIs that will allow these sorts of actions from multiple frontends (web, telegram, etc.). Therefore, this probably won't be a priority at this point. However, you are more than welcome to implement whatever fix you see fit and link it here.
