### ISSUE TITLE
ModuleNotFoundError: No module named 'binance'

### ISSUE THREAD

**Issue by SonOfCrypto** [ccxt/binance-trade-bot#133]
Hi, can maybe tell me someone what i am doing wrong?

After installing all requirements and adding my user.cfg i try to run the python comment `ModuleNotFoundError: No module named 'binance'` but it stops at line 15 an i am getting an error `ModuleNotFoundError: No module named 'binance'`

Kindest regards

**Comment by edeng23** [comment]
Try using pip3

**Comment by SonOfCrypto** [comment]
got it! thx!
`python3 -m pip install -r requirements.txt` and `python3 ./crypto_trading.py`
