### ISSUE TITLE
Idea: Remove concept of 'current coin'

### ISSUE THREAD

**Issue by j-waters** [ccxt/binance-trade-bot#135]
I was thinking about this after making #134.

Is keeping track of the 'current coin' even necessary? The scout method could be changed to work as follows:

1. Filter the enabled coins to find ones that have a high enough balance to be sold
2. For each of those coins, use the current scouting algorithm

I think that would be simple enough to do, and would fix issues like #75 better. 

This would then allow for the risk to be spread. At the moment as per #122 if there are multiple possible coins we could switch to, we pick the best one. If there was no concept of the 'current coin', we could instead switch from one coin to multiple different coins, and spread the risk. Or when switching to a coin, we could just convert half of the current coin, incase the current coin continues to spike.

I'd happily work on this if people think it's a good idea

**Comment by jeremiesigrist** [comment]
Yes I think it is a very good idea.

**Comment by rel-s** [comment]
I see the benefit of being able to "risk-spread", but this is probably hard to configure in the bot's current state... Did you have anything in mind about how to control this?

**Comment by johannes-peeters** [comment]
This would also allow to trade with multiple coins in parallel. Good idea!

**Comment by j-waters** [comment]
I don't have a concrete idea of how risk spreading would work. My pull request #137 doesn't do any of that yet.

@rel-s you're right it would be a bit tricky to configure. Maybe we could add a cooldown to each pair like so:

1. Switching from XLM to EOS
2. Current XLM balance is 100
3. 50 XLM -> EOS
4. Update XLM-> EOS ratio, and set an x minute cooldown on that pair
5. Continue scouting
6. x minute cooldown is up, if XLM->EOS is still a good idea then we either convert the other 50 XLM, or again just do half and set a cooldown, idk. The former would require looking up the previous trade in the database, the latter would mean that eventually we'd have too few XLM to trade, which isn't the end of the world but if you have too many coins and not enough total value the bot could get stuck. I'm sure we could add some logic so this doesn't happen

In this example the bot has performed better than it would have done previously

**Comment by Cactii1** [comment]
It seems that current coin is just a way to tell the bot which coin it's starting with. So it's the coin that you've loaded your Binance account with. Beyond being the initial trade coin it means nothing.

**Comment by danstis** [comment]
Spreading the risk could potentially be handled by buying coins in packages which are a fraction of the total available amount. 
Potentially we have a maximum concurrent coins variable that controls the size of the packages of coins that are initially traded.
We could continue to use the supported coins the way we do today to ensure it only selects from the desired coins.

So maybe the configured package quantity is 10 and we have a 200 base coin starting balance, we create 10x packages of 20 base coins to trade.

We would need to have some logic to help rebalance the packages as they grow or shrink, potentially this could be handled by leaving a small amount (configurable) in the base coin, which is re-evaluated each trade that is used to top up other packages that need additional funding.

**Comment by j-waters** [comment]
I'll close this since #204 is merged, and adds the `multiple_coins` strategy. I'll add to that strategy in the future to make it more configurable, and also add some of the suggestions from here
