### ISSUE TITLE
Binance exception if a coin is held to long?

### ISSUE THREAD

**Issue by SonOfCrypto** [ccxt/binance-trade-bot#144]
Got this exeption after 1h because there was no coin switch for 60 min.

`binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow`

**Comment by huukhanh** [comment]
>I have been syncing my host time with  time.google.com switched to time.nist.gov and it works finally

From Discord, you can try this.

**Comment by rel-s** [comment]
This error doesn't have anything to do with not switching a coin. There are closed issues with the same error, and you can also consult our Discord channel for more info.
