### ISSUE TITLE
Bot stuck at buying

### ISSUE THREAD

**Issue by HyperSound** [ccxt/binance-trade-bot#152]
The bot gets stuck at the buying process if the coin prize raises. This means that the open order doesnt get  filled. Can you put a cooldown on the filling so that it skips the order and cancels it after an certain amount of time? Thanks

**Comment by exter01** [comment]
I have same problem...

**Comment by ntamas94** [comment]
Same misses 0.00001 TUSD

**Comment by johannes-peeters** [comment]
Duplicate of #72

**Comment by rel-s** [comment]
Yep, we want to take care of this eventually but it really isn't as straightforward as adding a timer. You guys are welcome to join the discussion on #72, or our Discord channel.
