### ISSUE TITLE
Order never filled

### ISSUE THREAD

**Issue by ardgraft** [ccxt/binance-trade-bot#163]
Apologies if this is already in hand on another ticket....

When an order is placed, buy or sell, and the order is out priced because the market has changed so it moves way down the order list, never to be seen of again. 

Would it be better to automatically cancel the order after X amount of time and restart the scout for a different trade? Of course, we could be between trades and sat on the bridge coin. Either way, we would need to cover that scenario. 

1. Timeout on order is met
2. Cancel the order
3. Remember the current holding coin at that moment
4. Remove the history of the trade?

**Comment by rel-s** [comment]
Hi! We are working on this. Instead of apologizing, just check the open issues next time... This is a duplicate of #72. If you have something to contribute please do so there. Closing.
