### ISSUE TITLE
optimum scout_transaction_fee

### ISSUE THREAD

**Issue by tinkzoing** [ccxt/binance-trade-bot#165]
I don't understand the "scout_transaction_fee", what value should be set?

Mine is set at 0.001, and I am noticing loss in overall coins amount..

I don't have BNB in my account so the fee is 0.1% 

Which value should be set in scout_transaction_fee?

**Comment by ABTDoug** [comment]
I'm in the same boat, but I changed it to 0.01 and things looked better.
I'm still looking for the optimum setting.  I just launched it with 0.1 to see what it'll do.

**Comment by ghost** [comment]
0.100% are the default maker/taker fees on binance, so presumably 0.001 is the correct value for the transaction fee.
<img width="661" alt="Screenshot 2021-03-03 at 23 50 08" src="https://user-images.githubusercontent.com/43064219/109883309-85a5f680-7c7b-11eb-88b8-e76b05777b04.png">

**Comment by kvviyala** [comment]
May be this can be a variable depending on the bridge coin and if there is a balance of BNB in your wallet.

If there is no BNB then the transaction fee is set at 0.001. But if there is BNB in your wallet then the transaction fee will be set to 0.00075.

Something like a IFTTT statement

**Comment by Cactii1** [comment]
Could probably just look it up at https://binance-docs.github.io/apidocs/spot/en/#trade-fee-user_data and use the value from here...
