### ISSUE TITLE
"docker-compose build" is failing

### ISSUE THREAD

**Issue by DeadlyVirez** [ccxt/binance-trade-bot#168]
I am on current commit 
(d5753c8097cd48e0ea48c09ed8371a33e3d0520a)

and docker-compose build is failing with the message:

> ❯ docker-compose build
api uses an image, skipping
sqlitebrowser uses an image, skipping
Building crypto-trading
Step 1/9 : FROM --platform=$BUILDPLATFORM python:3.8 as builder
ERROR: Service 'crypto-trading' failed to build : failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument

**Comment by j-waters** [comment]
I've found the same thing, have just temporarily removed the `--platform=$BUILDPLATFORM` bit for the time being. @segersniels

**Comment by DeadlyVirez** [comment]
@j-waters works! thank you

**Comment by Pekafu** [comment]
Not exactly the same thing but atleast this way it gets updated:
```
docker buildx build --platform linux/amd64 . --tag binance_trader
docker-compose up -d
```

edit: 

I just tried to run the api_server with the current version and gunicorn doesn't find the api_server
I added ```--chdir binance_trade_bot``` to the ```docker-compose.yml``` command like this:


```
command: gunicorn --chdir binance_trade_bot api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
```

however after that change it gets stuck at this: 
```
from .config import Config
ImportError: attempted relative import with no known parent package
```

**Comment by DeadlyVirez** [comment]
seems to work with removing the `--platform=$BUILDPLATFORM`, though the binance_trader_api container starts then exits with the error:

> binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:43:16 +0000] [8] [INFO] Booting worker with pid: 8
binance_trader_api | [2021-03-04 19:43:16 +0000] [8] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()

**Comment by bacnh85** [comment]
I do hardcode in the Dockerfile, then able to build again.

`FROM --platform=linux/amd64 python:3.8 as builder`

**Comment by segersniels** [comment]
The new platform thingy in the Dockerfile is a docker buildkit specific thing. To build yourself I would suggest either enabling the buildkit or replacing it with your required platform like: linux/amd64.

https://docs.docker.com/develop/develop-images/build_enhancements/
