### ISSUE TITLE
no configuration file found

### ISSUE THREAD

**Issue by yacinos95** [ccxt/binance-trade-bot#17]
i keep getting no configuration file found message although i have created the user.cfg file
![Untitled](https://user-images.githubusercontent.com/51056473/106967029-b9f2c980-6746-11eb-821b-3ae72deefe4e.png)

**Comment by edeng23** [comment]
Try running the bot from its containing folder.

**Comment by yacinos95** [comment]
I did run it from the containing folder
Still same error
