### ISSUE TITLE
Signature for this request is not valid

### ISSUE THREAD

**Issue by DeadlyVirez** [ccxt/binance-trade-bot#172]
the newer commits really don't seem to work. I'm getting errors all the time and not a single trade in almost 2 days.

The DB still updates in the scout history though, so I'm not sure if the bot is still working.

![image](https://user-images.githubusercontent.com/24830874/109998620-b46eac00-7d11-11eb-854e-dcc0bbbe6134.png)

> 2021-03-04 16:39:59,456 - crypto_trader_logger - ERROR - Error while updating value history...
Traceback (most recent call last):
  File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/app/binance_trade_bot/auto_trader.py", line 165, in update_values
    balance = self.manager.get_currency_balance(coin.symbol)
  File "/app/binance_trade_bot/binance_api_manager.py", line 39, in get_currency_balance
    for currency_balance in self.BinanceClient.get_account()[u"balances"]:
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1022): Signature for this request is not valid.
> 2021-03-04 16:40:01,056 - crypto_trader_logger - ERROR - Error while updating value history...
> Traceback (most recent call last):
 > File "/app/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/app/binance_trade_bot/auto_trader.py", line 165, in update_values
    balance = self.manager.get_currency_balance(coin.symbol)
  File "/app/binance_trade_bot/binance_api_manager.py", line 39, in get_currency_balance
    for currency_balance in self.BinanceClient.get_account()[u"balances"]:
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1022): Signature for this request is not valid.

**Comment by DeadlyVirez** [comment]
I renewed the API secret / token. seems to work again, though the binance rest api server (docker) doesnt start correctly:

> binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:32:27 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:32:27 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:39:54 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:39:54 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [INFO] Booting worker with pid: 7
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
binance_trader_api | ModuleNotFoundError: No module named 'api_server'
binance_trader_api | [2021-03-04 19:41:28 +0000] [7] [INFO] Worker exiting (pid: 7)
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-03-04 19:41:28 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-03-04 19:43:16 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-03-04 19:43:16 +0000] [8] [INFO] Booting worker with pid: 8
binance_trader_api | [2021-03-04 19:43:16 +0000] [8] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()

**Comment by nanashj** [comment]
Tu

**Comment by nanashj** [comment]
User

**Comment by DeadlyVirez** [comment]
> Tu

Would you be so kind and elaborate?
