### ISSUE TITLE
Api_server not working with the latest dockerfile

### ISSUE THREAD

**Issue by Pekafu** [ccxt/binance-trade-bot#178]
Even though it's currently recommended to use official image it fails at the module api_server not found as gunicorn doesn't find the api_server
I tried adding ```--chdir binance_trade_bot``` to the docker-compose.yml command like this:

```command: gunicorn --chdir binance_trade_bot api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123```
however after that change it gets stuck at this:

```from .config import Config
ImportError: attempted relative import with no known parent package```

**Comment by segersniels** [comment]
Nothing much has changed compared to how it was before. So not entirely sure why there's missing stuff. @j-waters what exactly is this missing module?
