### ISSUE TITLE
Pin dependencies!

### ISSUE THREAD

**Issue by Knifa** [ccxt/binance-trade-bot#181]
Please pin your dependencies in `requirements.txt` so they don't change between builds! Could be related to #178 e.g.

**Comment by rel-s** [comment]
Agreed, we should do this...

**Comment by j-waters** [comment]
Would it also be a good idea to encourage people to use `virtualenv` instead of installing dependencies globally?

**Comment by rel-s** [comment]
I think we can leave that up to the user, I don't mind putting it in the `README` but I also don't want to clutter it.

**Comment by rel-s** [comment]
Done!
