### ISSUE TITLE
lets find a way to manage stuck orders

### ISSUE THREAD

**Issue by seccentral** [ccxt/binance-trade-bot#187]
So i have a buy order stuck for hours because the coin to be bought jumped in value and is unlikely to come down. 
Now, the bot will just endlessly wait there until the price drops. could be days/weeks or more. 
Now i am stuck with USDT in wallet and an order that is not fulfilled. 
To manually fix the situation i have to stop the bot, delete the database, start over. 
Would love to avoid this situation. 

Suggestion: automatic cancellation upon predefined or custom timeout (in user.cfg for example) and re-scouting.

**Comment by seccentral** [comment]
```
Time in force (timeInForce):

This sets how long an order will be active before expiration.

Status    Description
GTC    Good Til Canceled
An order will be on the book unless the order is canceled.
IOC    Immediate Or Cancel
An order will try to fill the order as much as it can before the order expires.
FOK    Fill or Kill
An order will expire if the full order cannot be filled upon execution.
```

This is from the binance api. It's a parameter in the order call and from the logs I see only GTC orders being placed. Isn't it better to change this to FOK ? At first glance, it seems like this is a better idea. 
I am not a coder and would like some input from someone who knows better.

**Comment by alienfrenZyNo1** [comment]
I'll buy the man a few coffees if this gets sorted! It really is the only downfall I have seen so far.

**Comment by rodrigo-itao** [comment]
I'm working on it. Hope to release my fork today

**Comment by AdrianoMartins** [comment]
What if we use the method get_order_book to get the price in the scout and change the order to market? It will make the scout more precise in relation to the order, and using market ensure the immediate execution.

**Comment by jpedro06** [comment]
> So i have a buy order stuck for hours because the coin to be bought jumped in value and is unlikely to come down.

I have the same problem.

I agree that the ordering pattern should be FOK, as the currency may rise rapidly and the order may not be fully fulfilled. I imagine that it is necessary to define an expiration date anyway.

In addition, after that time it would be necessary to recalculate which currency to buy or it may be better to set a default currency to buy when it is stuck.

**Comment by HeyImNotBob** [comment]
As a quick-and-dirty workaround, I've added a timeout of five minutes

https://github.com/HeyImNotBob/binance-trade-bot/commit/64fb90d598269f1e7fa96f8b30d89ae75e83798d

I haven't tested it enough yet

**Comment by rel-s** [comment]
Hi, this is a duplicate of #72. If you have anything to add please do it on that thread. Closing.
