### ISSUE TITLE
ERROR! Since there is no backup file, a proper coin name must be provided at init

### ISSUE THREAD

**Issue by sidharthb0** [ccxt/binance-trade-bot#19]
Hi, 

I'm trying to test out your bot but I keep getting the following error:
`ERROR!
Since there is no backup file, a proper coin name must be provided at init`

Steps I followed:
1. Cloned the repo
2. Installed requirements
3. Created a file called user.cfg and inserted the following:
`[binance_user_config]
api_key=***********************
api_secret_key=*******************
current_coin=XRP`

Any ideas as to what could be going wrong?

**Comment by edeng23** [comment]
I see that you set XRP as your current coin, did you add it to your supported coin list as well?

**Comment by sidharthb0** [comment]
Do you mean within the crypto_trading.py file? Yes I have.

Edit: I think I figured this out, there was an error in syntax sorry!
