### ISSUE TITLE
Running multiple instances on the same system.

### ISSUE THREAD

**Issue by Nik0gda** [ccxt/binance-trade-bot#193]
At the moment if the user runs 2 bots at the same time, they will interfere since they will be using the same db. This eliminates the possibility of using multiple sub-accounts on the same system.

Would be nice if somebody would make a pr in which the db name can be specified either by providing arguments at the script start, or in the config file.

**Comment by rodrigo-itao** [comment]
I'm using 4 bots at the same time and they are running fine.

Each bot is stored in a different folder, and each bot is running in a different terminal.

**Comment by Cactii1** [comment]
What happens when more than one get the same coin?

**Comment by rodrigo-itao** [comment]
Each bot has it's own DB. Each bot is running on a different virtualenv

**Comment by rodrigo-itao** [comment]
And I'm using different accounts for each bot

**Comment by Nik0gda** [comment]
> 
> 
> And I'm using different accounts for each bot

Are you using official docker image? And what OS are you running.

**Comment by rodrigo-itao** [comment]
I'm running on a VPS server with Ubuntu. I'm not using docker

**Comment by Nik0gda** [comment]
There is no issue found after more investigation
