### ISSUE TITLE
Raspberry 

### ISSUE THREAD

**Issue by lbpuma3** [ccxt/binance-trade-bot#194]
is it possible to use this software on a raspberry?
and if there is an error automatically restarts?

with the new web user interface.
How to?

**Comment by Pekafu** [comment]
ofc it is.
there is no web user interface yet (in master branch), but you can access the db using api_server.
failed api queries to the binance don't break the code

install requirements with pip3 install -r requirements
and run with python3 -m binance_trade_bot 
or perhaps screen -S binance_trade_bot python3 -m binance_trade_bot

or do you want something else?

**Comment by rel-s** [comment]
Hi, this doesn't seem to be a bug or issue with the bot. Please move this discussion to our Discord channel.
