### ISSUE TITLE
Bot uses all available bridge funds when switching coins

### ISSUE THREAD

**Issue by piwo76** [ccxt/binance-trade-bot#206]
I am not sure if this is intended behavior, but the bot uses all available bridge funds when switching from one coin to another. Yesterday I had some free USDT from another (manual) trade when the bot switched coins. When going from the bridged coin to the new coin it took them all. 

It might be a good idea to only use the amount which was used when going from the old coin to the bridge coin (or have an option for it in the config file)

**Comment by tr0mb1r** [comment]
as the most obvious solution is that you can switch the bridge funds for manual or bot trading. 
For example:
USDT - used by bot trading and BUSD - used for manual trading
