### ISSUE TITLE
Failed to Buy/Sell

### ISSUE THREAD

**Issue by kirkyb** [ccxt/binance-trade-bot#21]
Hi. I'm struggling to start the program and receive the failed to buy/sell error.

Everything is set up correctly including the API.

Any ideas please?

**Comment by edeng23** [comment]
Did you read the log file?

**Comment by bricemeunier** [comment]
Just try to sync your computer time with internet time, worked for me

**Comment by kirkyb** [comment]
I figured out that I had 2 issues. Yes my Debian machine was not syncing the time properly. My other issue was the bot was not implementing my starting token.

**Comment by edeng23** [comment]
Why didn't the bot implement your starting token?
