### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by rpeyyyy** [ccxt/binance-trade-bot#212]
hello ,after few hours... I have the latest version [https://pastebin.com/FMtc1AiF](url) What is happening?

**Comment by 3xtazzy** [comment]
It happened to me too, but does not affects bot performance. It does?

**Comment by remriel** [comment]
It's probably your internet

**Comment by mfcodeworks** [comment]
I'm also consistently getting this error within a DigitalOcean droplet which shouldn't have any network info.

There seems to be some good info on this [here](https://github.com/psf/requests/issues/4937), same error, looks like it's related to TCP keep alive messages and possibly Binance having lower limits

**Comment by rel-s** [comment]
This probably has nothing to do with the bot, if this is still an issue please move it to our Discord channel.
