### ISSUE TITLE
Backtesting feature

### ISSUE THREAD

**Issue by ilearnio** [ccxt/binance-trade-bot#214]
It would be great if there was a way to test how much money the bot could make during a specified period of time by feeding it with historical data from Binance. This way it would be clear how good is the strategy and would allow to test it on different crypto currencies without spending money. I'm wondering if you have any plans for adding such functionality

**Comment by ryansonshine** [comment]
Looks like this PR includes the functionality you're asking about: https://github.com/edeng23/binance-trade-bot/pull/196
