### ISSUE TITLE
APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE

### ISSUE THREAD

**Issue by xioxu** [ccxt/binance-trade-bot#231]
The following content is from my user.cfg :

[binance_user_config]
api_key=XXXXXXXXXX
api_secret_key=XXXXXXXXXXXX
current_coin=
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=300
strategy=default

**As you can see, I had increased the scout_sleep_time to 300 seconds, but the issue still hapen per minutes.**
The version I'm using is 4806f0ff871704a8bb71241c617e8c94b479e281 , the latest version until 23/Mar

Error while updating value history...
Traceback (most recent call last):
  File "/root/bitcoin_bot/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.6/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/root/bitcoin_bot/binance-trade-bot/binance_trade_bot/auto_trader.py", line 165, in update_values
    all_ticker_values = self.manager.get_all_market_tickers()
  File "/root/bitcoin_bot/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 61, in get_all_market_tickers
    return self.binance_client.get_all_tickers()
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 437, in get_all_tickers
    return self._get(&apos;ticker/price&apos;, version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 237, in _get
    return self._request_api(&apos;get&apos;, path, signed, version, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by xuantinfx** [comment]
I have the same issue

**Comment by xioxu** [comment]
I even also changed "current_coin", but still not works.

**Comment by j-waters** [comment]
This is a known issue, that will be fixed by #211 and/or #208. `BinanceAPIManager.get_fee()` is called very often, and causes a lot of API requests. There are three solutions currently:

1. Reduce the number of enabled coins, ie remove coins from your `supported_coins_list` file and restart the bot
2. Modify the `BinanceAPIManager.get_fee()` method to only return `0.001`
3. Go back to commit 7e1f72c80d1e6ef05249baff865c1df6c2e1a095

**Comment by xioxu** [comment]
Thanks, back to commit "7e1f72c80d1e6ef05249baff865c1df6c2e1a095" solved this issue!

**Comment by danstis** [comment]
Keep in mind that if anyone is running the docker container from docker hub, then they can't do any of the above options. We don't have tags on branches, and we don't have tags on previous commits.

**Comment by yipikaye** [comment]
> Keep in mind that if anyone is running the docker container from docker hub, then they can't do any of the above options. We don't have tags on branches, and we don't have tags on previous commits.

I updated my docker-compose.yaml to reduce the supported coins list. cake. 

  crypto-trading:
    image: edeng23/binance-trade-bot
    container_name: binance_trader
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./data:/app/data
      - ./logs:/app/logs
      - ./supported_coin_list:/app/supported_coin_list
    command: python -m binance_trade_bot

**Comment by kloudmuka** [comment]
Does this problem get fixed? I still got this error.

**Comment by itlboy** [comment]
me too

**Comment by jbalatero** [comment]
me as well

**Comment by jbalatero** [comment]
>Thanks, back to commit "7e1f72c80d1e6ef05249baff865c1df6c2e1a095" solved this issue!

Fixed me as well, but I have to remove all .db files in data directory.

**Comment by Han0nly** [comment]
Still got this issue

**Comment by rel-s** [comment]
We are hopefully adding websocket support soon, so this should be solved (or at least substantially reduced). Closing this for duplication.

**Comment by sbhadade** [comment]
@j-waters i am still getting this issue. Please guide

**Comment by sbhadade** [comment]
binance.exceptions.BinanceAPIException: APIError(code=-1003): Way too much request weight used; IP banned until 1634267676397. Please use the websocket for live updates to avoid bans.

**Comment by Loltree** [comment]
@sbhadade did you solve it?
