### ISSUE TITLE
Trade with a defined amount

### ISSUE THREAD

**Issue by moafred** [ccxt/binance-trade-bot#236]
Hello!

Is it possible to set the amount (bridge currency) with which the bot can trade ?

I want to keep trading on my own alongside the bot :)

Thanks

**Comment by edeng23** [comment]
@moafred, no, not at the moment. As mentioned, PR #237 will allow this. Since I haven't tested it yet, and there are a few PRs that we want to merge first, I suggest that you use the trivial workaround for now - using a different stable coin for personal trading.

**Comment by moafred** [comment]
@edeng23 good idea for the workaround. Yeah i see very interesting features in PR that are more usefull that my need ! Thanks dude
