### ISSUE TITLE
current_coin_history not showing up in database

### ISSUE THREAD

**Issue by DeadlyVirez** [ccxt/binance-trade-bot#241]
Database seems to not be tracking current_coin_history since newest commit (9d4db23aac30fdbd4a41ddd33ce353260e320ea6)

![image](https://user-images.githubusercontent.com/24830874/112374435-603c6380-8ce2-11eb-9a38-ea511c31ac2a.png)

**Comment by GrigorovskyA** [comment]
@DeadlyVirez which strategy do you use?

**Comment by DeadlyVirez** [comment]
I am on `multiple_coins`
I guess that makes sense then?
I'm sorry but I don't understand the code.

**Comment by GrigorovskyA** [comment]
Yes, that's right, the `multiple_coins` strategy does nothing with the table.

**Comment by DeadlyVirez** [comment]
Okay that's good to know. Thank you!
