### ISSUE TITLE
It's importance for getting all filters once when initialiazation is better than get it before each order

### ISSUE THREAD

**Issue by beaquant** [ccxt/binance-trade-bot#249]
getting all filters once when initialiazation with cache is better than get it before each order
because the filters low probability of being changed. It's a big waste reuqest limitation!

https://github.com/edeng23/binance-trade-bot/blob/9d4db23aac30fdbd4a41ddd33ce353260e320ea6/binance_trade_bot/binance_api_manager.py#L102

**Comment by j-waters** [comment]
The result is cached for 12 hours:
https://github.com/edeng23/binance-trade-bot/blob/9d4db23aac30fdbd4a41ddd33ce353260e320ea6/binance_trade_bot/binance_api_manager.py#L101

We could probably store all this permanently but on the slim chance something changes we may as well just cache it like this
