### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by danvilar** [ccxt/binance-trade-bot#25]
Hi, I have been running the bot for 4 days so far. I believe that the scouting shouldn't be included in the log because it doesn't provide any useful information and just contributes to large log files. My log file is now effectively 22k lines long. Also, I can provide you with the trades the bot performed for analysis if that's something you are interested in.

**Comment by SaltySousChef** [comment]
I am just here browsing but I am very interested in your results, please share.

**Comment by danvilar** [comment]
Here is the lean version of the log: https://gist.github.com/danvilar/661f967b8fb06a4d5fb986fdde8061b1.
It started by selling 0.0398 ETH and after 4 days it was able to buy 0.041 ETH. I believe that the algorithm is working quite well.

**Comment by SaltySousChef** [comment]
Nice, 3% extra! I am going to have a go. I figure if I only allow it to trade coins I wouldn't mind ending up with there's not much to lose.

**Comment by ivanyyw** [comment]
You can easy remove the scouting info by putting #:

```
def scout(client, transaction_fee=0.001, multiplier=5):
    '''
    Scout for potential jumps from the current coin to another coin
    '''
    #logger.info("Scouting...")
    global g_state
```

**Comment by edeng23** [comment]
Agreed, I deleted it. 
Thanks for the information! It's fun to see that the bot is effective. That being said, I usually get better results in the first few days of running it 😄 .
