### ISSUE TITLE
bridge_scout function delaying regular scouting

### ISSUE THREAD

**Issue by CTetford** [ccxt/binance-trade-bot#250]
When using the multiple_coins strategy, calling bridge_scout at the end of each round of scouting causes the program to iterate through every supported pair's ratio (even if it doesn't contain a substantial balance) to check which one to buy with the remaining bridge.

This causes a significant delay between each round of scouting.

It may be better to modify bridge_scout to only run through all the pairs if a substantial balance actually exists that needs to be changed back to crypto, to avoid wasting time that could be scouting.

**Comment by yubina** [comment]
0.734 buy
0.729 sell
not all coins are the same .btt

**Comment by CTetford** [comment]
Disregard this, when using the upcoming websocket addition it doesn't matter.
