### ISSUE TITLE
Possibility to run the bot DRY

### ISSUE THREAD

**Issue by porcherie** [ccxt/binance-trade-bot#257]
Would be super cool to add a feature to run the bot dry, basically simulating trades, as it is possible on other bots.
It would give me, and I guess other users too, more peace of mind when testing.

**Comment by matthewiiv** [comment]
+1 this. As far as I can tell binance doesn't have a sandox api for anything except futures. How have others been testing?

**Comment by porcherie** [comment]
I am using freqtrade in dry mode without problems, unfortunately I cannot give you more details because I don't know how it works under the hood, but you can easily find it here in GitHub

**Comment by werim** [comment]
https://testnet.binance.vision/

**Comment by j-waters** [comment]
You can use the backtesting system, and it shouldn't be too hard to modify that to run the bot dry in real time, if someone wants to make a PR
