### ISSUE TITLE
can't run the bot!!

### ISSUE THREAD

**Issue by allaf2** [ccxt/binance-trade-bot#274]
hello.
i cant run the bot on centos7 docker.

my user.cfg  is:

`[binance_user_config]
api_key=*******3LRU653HyjS36FY404rSgAbkPEpmEqL********
api_secret_key=*********BMezKizcBscLKsz4BpXpUY8*********
current_coin= "XLM TRX ICX EOS IOTA ONT QTUM ETC ADA XMR DASH NEO ATOM DOGE VET BAT OMG BTT"
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=5
strategy=default
buy_timeout=0
sell_timeout=0`

and the error is:

sqlitebrowser     | Starting guacamole-lite websocket server
sqlitebrowser     | listening on *:3000
binance_trader    | 2021-04-14 12:30:51,465 - crypto_trading_logger - INFO - Starting
binance_trader    | Traceback (most recent call last):
binance_trader    |   File "/usr/local/lib/python3.8/configparser.py", line 789, in get
binance_trader    |     value = d[option]
binance_trader    |   File "/usr/local/lib/python3.8/collections/__init__.py", line 898, in __getitem__
binance_trader    |     return self.__missing__(key)            # support subclasses that define __missing__
binance_trader    |   File "/usr/local/lib/python3.8/collections/__init__.py", line 890, in __missing__
binance_trader    |     raise KeyError(key)
binance_trader    | KeyError: 'current_coin'
binance_trader    |
binance_trader    | During handling of the above exception, another exception occurred:
binance_trader    |
binance_trader    | Traceback (most recent call last):
binance_trader    |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
binance_trader    |     return _run_code(code, main_globals, None,
binance_trader    |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
binance_trader    |     exec(code, run_globals)
binance_trader    |   File "/app/binance_trade_bot/__main__.py", line 5, in <module>
binance_trader    |     main()
binance_trader    |   File "/app/binance_trade_bot/crypto_trading.py", line 16, in main
binance_trader    |     config = Config()
binance_trader    |   File "/app/binance_trade_bot/config.py", line 67, in __init__
binance_trader    |     self.CURRENT_COIN_SYMBOL = os.environ.get("CURRENT_COIN_SYMBOL") or config.get(USER_CFG_SECTION, "current_coin")
binance_trader    |   File "/usr/local/lib/python3.8/configparser.py", line 792, in get
binance_trader    |     raise NoOptionError(option, section)
binance_trader    | configparser.NoOptionError: No option 'current_coin' in section: 'binance_user_config'
binance_trader_api | [2021-04-14 12:30:53 +0000] [9] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/configparser.py", line 789, in get
binance_trader_api |     value = d[option]
binance_trader_api |   File "/usr/local/lib/python3.8/collections/__init__.py", line 898, in __getitem__
binance_trader_api |     return self.__missing__(key)            # support subclasses that define __missing__
binance_trader_api |   File "/usr/local/lib/python3.8/collections/__init__.py", line 890, in __missing__
binance_trader_api |     raise KeyError(key)
binance_trader_api | KeyError: 'api_key'
binance_trader_api |
binance_trader_api | During handling of the above exception, another exception occurred:
binance_trader_api |
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
binance_trader_api |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
binance_trader_api |   File "/app/binance_trade_bot/api_server.py", line 24, in <module>
binance_trader_api |     config = Config()
binance_trader_api |   File "/app/binance_trade_bot/config.py", line 49, in __init__
binance_trader_api |     self.BINANCE_API_KEY = os.environ.get("API_KEY") or config.get(USER_CFG_SECTION, "api_key")
binance_trader_api |   File "/usr/local/lib/python3.8/configparser.py", line 792, in get
binance_trader_api |     raise NoOptionError(option, section)
binance_trader_api | configparser.NoOptionError: No option 'api_key' in section: 'binance_user_config'
binance_trader_api | [2021-04-14 12:30:53 +0000] [9] [INFO] Worker exiting (pid: 9)
binance_trader_api | No configuration file (user.cfg) found! See README. Assuming default config...
binance_trader_api | [2021-04-14 12:30:53 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-04-14 12:30:53 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader exited with code 1
binance_trader_api exited with code 3
^CGracefully stopping... (press Ctrl+C again to force)
Killing sqlitebrowser       ... done
^C
[root@s2 edeng23]# docker-compose up
Starting binance_trader ... done
Starting sqlitebrowser  ... done
Starting binance_trader_api ... done
Attaching to sqlitebrowser, binance_trader, binance_trader_api
sqlitebrowser     | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
sqlitebrowser     | [s6-init] ensuring user provided files have correct perms...exited 0.
sqlitebrowser     | [fix-attrs.d] applying ownership & permissions fixes...
sqlitebrowser     | [fix-attrs.d] done.
sqlitebrowser     | [cont-init.d] executing container initialization scripts...
sqlitebrowser     | [cont-init.d] 01-envfile: executing...
sqlitebrowser     | [cont-init.d] 01-envfile: exited 0.
sqlitebrowser     | [cont-init.d] 10-adduser: executing...
sqlitebrowser     | usermod: no changes
sqlitebrowser     |
sqlitebrowser     | -------------------------------------
sqlitebrowser     |           _         ()
sqlitebrowser     |          | |  ___   _    __
sqlitebrowser     |          | | / __| | |  /  \
sqlitebrowser     |          | | \__ \ | | | () |
sqlitebrowser     |          |_| |___/ |_|  \__/
sqlitebrowser     |
sqlitebrowser     |
sqlitebrowser     | Brought to you by linuxserver.io
sqlitebrowser     | -------------------------------------
sqlitebrowser     |
sqlitebrowser     | To support the app dev(s) visit:
sqlitebrowser     | DB Browser for SQLite: https://www.patreon.com/db4s
sqlitebrowser     |
sqlitebrowser     | To support LSIO projects visit:
sqlitebrowser     | https://www.linuxserver.io/donate/
sqlitebrowser     | -------------------------------------
sqlitebrowser     | GID/UID
sqlitebrowser     | -------------------------------------
sqlitebrowser     |
sqlitebrowser     | User uid:    1000
sqlitebrowser     | User gid:    1000
sqlitebrowser     | -------------------------------------
sqlitebrowser     |
sqlitebrowser     | [cont-init.d] 10-adduser: exited 0.
sqlitebrowser     | [cont-init.d] 12-prep_xrdp: executing...
sqlitebrowser     | [cont-init.d] 12-prep_xrdp: exited 0.
sqlitebrowser     | [cont-init.d] 30-config: executing...
sqlitebrowser     | [cont-init.d] 30-config: exited 1.
sqlitebrowser     | [cont-init.d] 55-autostart-config: executing...
sqlitebrowser     | [cont-init.d] 55-autostart-config: exited 0.
sqlitebrowser     | [cont-init.d] 99-custom-scripts: executing...
sqlitebrowser     | [custom-init] no custom files found exiting...
sqlitebrowser     | [cont-init.d] 99-custom-scripts: exited 0.
sqlitebrowser     | [cont-init.d] done.
sqlitebrowser     | [services.d] starting services
sqlitebrowser     | [services.d] done.
sqlitebrowser     | guacd[338]: INFO:   Guacamole proxy daemon (guacd) version 1.1.0 started
sqlitebrowser     | guacd[338]: INFO:   Listening on host 0.0.0.0, port 4822
binance_trader_api | [2021-04-14 12:33:02 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-04-14 12:33:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-04-14 12:33:02 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-04-14 12:33:02 +0000] [8] [INFO] Booting worker with pid: 8
sqlitebrowser     | Starting guacamole-lite websocket server
sqlitebrowser     | listening on *:3000
binance_trader    | 2021-04-14 12:33:04,862 - crypto_trading_logger - INFO - Starting
binance_trader    | 2021-04-14 12:33:05,699 - crypto_trading_logger - INFO - Chosen strategy: default
binance_trader    | 2021-04-14 12:33:05,699 - crypto_trading_logger - INFO - Creating database schema if it doesn't already exist
binance_trader_api | [2021-04-14 12:33:05 +0000] [8] [ERROR] Exception in worker process
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/configparser.py", line 789, in get
binance_trader_api |     value = d[option]
binance_trader_api |   File "/usr/local/lib/python3.8/collections/__init__.py", line 898, in __getitem__
binance_trader_api |     return self.__missing__(key)            # support subclasses that define __missing__
binance_trader_api |   File "/usr/local/lib/python3.8/collections/__init__.py", line 890, in __missing__
binance_trader_api |     raise KeyError(key)
binance_trader_api | KeyError: 'api_key'
binance_trader_api |
binance_trader_api | During handling of the above exception, another exception occurred:
binance_trader_api |
binance_trader_api | Traceback (most recent call last):
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
binance_trader_api |     worker.init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
binance_trader_api |     super().init_process()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
binance_trader_api |     self.load_wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
binance_trader_api |     self.wsgi = self.app.wsgi()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
binance_trader_api |     self.callable = self.load()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
binance_trader_api |     return self.load_wsgiapp()
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
binance_trader_api |     return util.import_app(self.app_uri)
binance_trader_api |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
binance_trader_api |     mod = importlib.import_module(module)
binance_trader_api |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
binance_trader_api |     return _bootstrap._gcd_import(name[level:], package, level)
binance_trader_api |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
binance_trader_api |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
binance_trader_api |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
binance_trader_api |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
binance_trader_api |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
binance_trader_api |   File "/app/binance_trade_bot/api_server.py", line 24, in <module>
binance_trader_api |     config = Config()
binance_trader_api |   File "/app/binance_trade_bot/config.py", line 49, in __init__
binance_trader_api |     self.BINANCE_API_KEY = os.environ.get("API_KEY") or config.get(USER_CFG_SECTION, "api_key")
binance_trader_api |   File "/usr/local/lib/python3.8/configparser.py", line 792, in get
binance_trader_api |     raise NoOptionError(option, section)
binance_trader_api | configparser.NoOptionError: No option 'api_key' in section: 'binance_user_config'
binance_trader_api | [2021-04-14 12:33:05 +0000] [8] [INFO] Worker exiting (pid: 8)
binance_trader_api | No configuration file (user.cfg) found! See README. Assuming default config...
binance_trader_api | [2021-04-14 12:33:06 +0000] [1] [INFO] Shutting down: Master
binance_trader_api | [2021-04-14 12:33:06 +0000] [1] [INFO] Reason: Worker failed to boot.
binance_trader    | 2021-04-14 12:33:06,718 - crypto_trading_logger - INFO - Setting initial coin to "XLM TRX ICX EOS IOTA ONT QTUM ETC ADA XMR DASH NEO ATOM DOGE VET BAT OMG BTT"
binance_trader    | ***
binance_trader    | ERROR!
binance_trader    | Since there is no backup file, a proper coin name must be provided at init
binance_trader    | ***
binance_trader exited with code 1
binance_trader_api exited with code 3

please help me.

thanks

**Comment by LetsMelon** [comment]
It doesn't work for me with docker-compose either, just start it normally with python.
I had the same error `KeyError: 'api_key'`

**Comment by allaf2** [comment]
thanks bro.
i will try.

**Comment by allaf2** [comment]
which version of python needed?
my versions is 2.7 and 3.8

**Comment by jawak** [comment]
edit docker-compose.yml
add in api 
volumes:
      - ./user.cfg:/app/user.cfg

**Comment by allaf2** [comment]
> 
> 
> edit docker-compose.yml
> add in api
> volumes:
> - ./user.cfg:/app/user.cfg

thanks bro.
 now stuck in: 

binance_trader_api | [2021-04-15 09:08:30 +0000] [1] [INFO] Starting gunicorn 20.0.4
binance_trader_api | [2021-04-15 09:08:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:5123 (1)
binance_trader_api | [2021-04-15 09:08:30 +0000] [1] [INFO] Using worker: eventlet
binance_trader_api | [2021-04-15 09:08:30 +0000] [8] [INFO] Booting worker with pid: 8
binance_trader    | 2021-04-15 09:08:32,502 - crypto_trading_logger - INFO - Starting
binance_trader    | 2021-04-15 09:08:33,322 - crypto_trading_logger - INFO - Chosen strategy: default
binance_trader    | 2021-04-15 09:08:33,322 - crypto_trading_logger - INFO - Creating database schema if it doesn't already exist
