### ISSUE TITLE
How to trade multiple coins in parallel?

### ISSUE THREAD

**Issue by MrsBookik** [ccxt/binance-trade-bot#286]
Hi, according to README I thought that the setting

`strategy=multiple_coins`

in `user.cfg` would enable us to trade multiple coins in parallel. However I see always only one trade in active tradelist consuming all available funds.

What am I missing here?

**Comment by j-waters** [comment]
The strategy isn't really finished, at the moment it's main benefit is that it is slightly more stable than the default strategy. 

Say you have XLM, ETH, IOTA and DOGE in your supported coins list, and you have some XLM in your account and nothing else. The bot will jump between the coins, using that full balance each time, only really holding one coin at a time. 

If you manually distribute some of your balance, so you have some XLM and some ETH, the bot will trade in parallel. However, at the moment, there's a high chance that the bot will end up trading both coins to the same coin so you go back to only having one active coin. Eg: the bot does XLM -> IOTA and ETH -> IOTA at the same time. Now you have only IOTA and nothing else, and from then on the bot will trade that full amount around.

Eventually I'll improve the strategy so it works more like you'd expect, keeping multiple coins active at once, not trading the full amount each time, etc. You can always make a custom strategy that does this if you like

If a Discord mod comes across this it might be nice to add to the FAQ?
