### ISSUE TITLE
Are only those coins supported that are part of the file "supported_coin_list"?

### ISSUE THREAD

**Issue by MrsBookik** [ccxt/binance-trade-bot#287]
The repo has a file with the name `supported_coin_list`, consisting of a list of coins.

Can we add more coins in the user.cfg, that aren't listed in that file or is this the de-facto-list of those coins, that are *really* supported yet?

**Comment by AfiqHasiff** [comment]
List of coins that works with the bot from the discord group https://pastebin.com/efAgh2vY

**Comment by Blaklis** [comment]
You can't add anything to the `user.cfg` - the `supported_coin_list` is the file that manages what coins your bot will be allowed to trade with. So you can add whatever is on Binance in it, and your bot will eventually trade with it.

**Comment by andy3520** [comment]
I've checked the list of @AfiqHasiff , deduplicate and remove the error coin and this is my final list https://gist.github.com/andy3520/8f9534fec85f8bea76b0dd3bc742f0d3
