### ISSUE TITLE
Docker: Apprise config not imported to volume

### ISSUE THREAD

**Issue by horstefan** [ccxt/binance-trade-bot#288]
When using docker, apprise config is not imported.

**Comment by rel-s** [comment]
Any docker users encountering this issue? Please add more information (a PR would be best).

**Comment by horstefan** [comment]
Please add       - ./config/apprise.yml:/app/config/apprise.yml to Volumes in docker-compose.yml
im not too familiar with creating/managing PR's. apologies.

**Comment by lixifumi** [comment]
Solved #331
