### ISSUE TITLE
can u?

### ISSUE THREAD

**Issue by MBillar** [ccxt/binance-trade-bot#29]
Maybe u can make it for list of coins, not only 4 one?)

**Comment by ivanyyw** [comment]
Just make your own adjustment at 
crypto_trading.py:

`supported_coin_list = [u'coin1', u'coin2', u'coin3']`

**Comment by MBillar** [comment]
> Just make your own adjustment at
> crypto_trading.py:
> 
> `supported_coin_list = [u'coin1', u'coin2', u'coin3']`

I mean, it starting by 1 coin wich presets in config. better if it can work with all coins on balance

**Comment by electrotelco** [comment]
It would be ideal to be able to start the work from USDT, sometimes it is very difficult to decide where to start

**Comment by edeng23** [comment]
Starting from USDT is now possible.
