### ISSUE TITLE
skipping buy / sell step

### ISSUE THREAD

**Issue by romanhrbaty** [ccxt/binance-trade-bot#299]
Can bot skip intermediate steps in the purchase?
like buy / sell DOT (in the example below) a jump to last buy?

binance-trade-bot, [25.04.21 11:37]
Sold DIA

binance-trade-bot, [25.04.21 11:37]
BUY QTY 7.671

binance-trade-bot, [25.04.21 11:38]
Bought DOT

binance-trade-bot, [25.04.21 11:38]
Will be jumping from <DOT> to BCH

binance-trade-bot, [25.04.21 11:38]
Selling 7.671 of DOT

binance-trade-bot, [25.04.21 11:38]
Balance is 7.6711995

binance-trade-bot, [25.04.21 11:38]
order

binance-trade-bot, [25.04.21 11:38]
Waiting for Binance

binance-trade-bot, [25.04.21 11:38]
Sold DOT

binance-trade-bot, [25.04.21 11:38]
BUY QTY 0.30092

binance-trade-bot, [25.04.21 11:38]
Bought BCH

**Comment by rel-s** [comment]
Hi, the purpose of the bot is to maximize coin gain through price diffs. Please see the README to better understand the trading logic.
