### ISSUE TITLE
Stuck on the first scout

### ISSUE THREAD

**Issue by FlyingShuriken** [ccxt/binance-trade-bot#301]
My script always pick ONTUSDT as the first scout, and stuck on it until I stop the script.

this is my user.cfg:
`[binance_user_config]
api_key=...
api_secret_key=...
current_coin= "VET BAT BTT DOGE EOS ETC TRX XLM XMR RUNE THETA XRP"
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=5
strategy=default
buy_timeout=0
sell_timeout=0
`

ONT is not in my current_coin and supported_coin_list file.

This is the console:
`2021-04-27 08:36:35,210 - crypto_trading_logger - INFO - Starting
2021-04-27 08:36:35,808 - crypto_trading_logger - INFO - Chosen strategy: default
2021-04-27 08:36:35,809 - crypto_trading_logger - INFO - Creating database schema if it doesn't already exist
2021-04-27 08:38:47.519449 - CONSOLE - INFO - I am scouting the best trades. Current coin: ONTUSDT`

**Comment by AfiqHasiff** [comment]
Current coin should be only one coin which is the coin youre currently holding. Theres also a seperate file for coin list and it shouldnt be in user.cfg.

**Comment by FlyingShuriken** [comment]
> Current coin should be only one coin which is the coin youre currently holding. Theres also a seperate file for coin list and it shouldnt be in user.cfg.

Thanks!
