### ISSUE TITLE
Automatic supported_coin_list

### ISSUE THREAD

**Issue by werim** [ccxt/binance-trade-bot#304]
Everyday new coins listing on Binance that have potential to pump. Besides updating supported_coin_list daily, pull the desired coin list from Binance.

**Comment by werim** [comment]
config.echangeinfo

**Comment by juanmzaragoza** [comment]
Are you sure about that? If you see the time of response when you request to get_fee service, you will see that response time increases from pair 32  processed.
For this reason, I take a random sample from all pairs enabled to avoid an excessive response time.

**Comment by rel-s** [comment]
Hi, feel free to create a PR and implement this. On top of that, Github Issues for this project are not meant for feature requests so please move this discussion to our Discord channel.
