### ISSUE TITLE
Profit.py

### ISSUE THREAD

**Issue by werim** [ccxt/binance-trade-bot#306]
Profit module that lists transactions and earnings by coin.

**Comment by horstefan** [comment]
When u use the Guacamole client (on 0.0.0.0:3000) 
-Open the db. (/data/crypto_trading.db)
-go to "browse data" and show the table "trade history"
-on the bottom right select "plot" 

-set crypto_trade_amount on Y-axis
-set datetime on X-axis

edit: downside is its needs manual refreshing :) maybe someone can improve.

**Comment by rel-s** [comment]
Hi, feel free to create a PR and implement this. On top of that, Github Issues for this project are not meant for feature requests so please move this discussion to our Discord channel.
