### ISSUE TITLE
Calling too much GetAllTickers(), exceeding 1200 upper API limit

### ISSUE THREAD

**Issue by innocentius** [ccxt/binance-trade-bot#307]
Shout out to #231. 

It has come to my attention that binance recently (again) modified weights used in API. This is causing the program to exceed the upper limit weight due to frequent calling of get_all_market_tickers().

For now my solution is to add time.sleep(2) to slow down the program, but this issue would not be fixed without we implement websocket live updates functions.

**Comment by jonwilliams84** [comment]
I am also getting this. @innocentius where in the code did you add the sleep?

**Comment by innocentius** [comment]
@jonwilliams84 go to binance_api_manager.py, 
add a line before the return statement of the specific function, like this

```python

    def get_all_market_tickers(self) -> AllTickers:
        """
        Get ticker price of all coins
        """
        time.sleep(2)
        return AllTickers(self.binance_client.get_all_tickers())
```

Beware that the update market ticker function cost 10 weight per call, with a 1200 weight pool/minute for ALL OF YOUR ACTIONS, include trading. I tested time.sleep(1) (i.e.: forcing the program to sleep for 1 second), and it usually run out of quota at the 58s mark. 
time.sleep(2) give you probably a bit more than 300 weight left (i suppose...), whether it is enough for other activities, I'm not sure.

**Comment by jonwilliams84** [comment]
Thats great thanks - I managed to work it out just before you posted. :-)

I assume this depends on the number of supported coins, the more coins the more likely you'll be rate limited?

I agree this doesn't really fix it unless the bot moves to a websocket.

**Comment by innocentius** [comment]
> I assume this depends on the number of supported coins, the more coins the more likely you'll be rate limited?

@jonwilliams84 That is probably not the case. The function called would like to "get...price of all coins", so that it doesn't matter how many coins you make the program support, nor does it matter how much kinds of coin you have in your wallet.

**Comment by kevinunger** [comment]
Wouldn't this problem be solved by using the websocket API of binance?

**Comment by phuongtai** [comment]
In my opinion, it's not actually calling `get_all_market_tickers ` too much, I did some tests, the bot calls`get_currency_balance` many time within the increasing of weight request recently of Binance API, cause this problem.

> On April 28, 2021 00:00 UTC the weights to the following endpoints will be adjusted:

> GET /api/v3/order weight increased to 2
> GET /api/v3/openOrders weight increased to 3
> GET /api/v3/allOrders weight increased to 10
> GET /api/v3/orderList weight increased to 2
> GET /api/v3/openOrderList weight increased to 3
> GET /api/v3/account weight increased to 10
> GET /api/v3/myTrades weight increased to 10
> GET /api/v3/exchangeInfo weight increased to 10


https://binance-docs.github.io/apidocs/spot/en/#change-log

**Comment by nunocoracao** [comment]
Any idea when this will be fixed?

**Comment by phuongtai** [comment]
For reducing number of requests, just use TTLCache with `max-size` and `ttl`(Time to live) you need

**Comment by To0wnn** [comment]
What do you advise? for max-size and ttl? And what is line number?

> For reducing number of requests, just use TTLCache with `max-size` and `ttl`(Time to live) you need

**Comment by nunocoracao** [comment]
Adding to @To0wnn question how can I use those parameters?

**Comment by phuongtai** [comment]
you guys can find some idea right here:
https://github.com/phuongtai/binance-trade-bot/blob/922c45f461a9abd37bc6864b5d7b7b0cd7d9fa41/binance_trade_bot/binance_api_manager.py#L70-L94

**Comment by innocentius** [comment]
> In my opinion, it's not actually calling `get_all_market_tickers ` too much, I did some tests, the bot calls`get_currency_balance` many time within the increasing of weight request recently of Binance API, cause this problem.
> 
> > On April 28, 2021 00:00 UTC the weights to the following endpoints will be adjusted:
> 
> > GET /api/v3/order weight increased to 2
> > GET /api/v3/openOrders weight increased to 3
> > GET /api/v3/allOrders weight increased to 10
> > GET /api/v3/orderList weight increased to 2
> > GET /api/v3/openOrderList weight increased to 3
> > GET /api/v3/account weight increased to 10
> > GET /api/v3/myTrades weight increased to 10
> > GET /api/v3/exchangeInfo weight increased to 10
> 
> https://binance-docs.github.io/apidocs/spot/en/#change-log

@phuongtai I'm not sure which method is being called too much, but it would definitely be a good idea to add a quota calculator in future development... even though I'm not sure if this thing is in active development or not.

**Comment by rel-s** [comment]
Current official fix is to increase scout time in `user.cfg`, this will probably be fixed (or at least better) with the upcoming websocket PR.
