### ISSUE TITLE
Main coin price caching

### ISSUE THREAD

**Issue by abanchev** [ccxt/binance-trade-bot#31]
When the trade threshold is being updated the current_coin price is requested on each loop iteration. Why not calculate it once before the loop and reuse it inside. This may get a price that is couple of seconds stale, but improves the performance a lot.

The same for the scouting, we could calculate the curr_coin_price before the loop, and if a trade jump occurs we can break out of the loop

**Comment by edeng23** [comment]
Sounds like a good idea. In addition to the performance case, it also makes more sense to save the "stale" price rather than the more recent one because it is closer to the time of the trade.
Do you want to make a pull request?
