### ISSUE TITLE
APIError(code=-1013): Invalid quantity

### ISSUE THREAD

**Issue by idsulik** [ccxt/binance-trade-bot#315]
I'm getting the error - `APIError(code=-1013): Invalid quantity`, how to fix it?
![image](https://user-images.githubusercontent.com/3595194/116822369-22571880-ab87-11eb-97c5-a1e101b1bf0c.png)

**Comment by bobstay** [comment]
hi its about quantity of crypto bridge i think

**Comment by jegerima** [comment]
I think you need to have some USDT to start. I changed my BNB to USDT and it works

**Comment by idsulik** [comment]
@jegerima , thank you, I will try.   
It will be useful if log message will be more clear)

**Comment by idsulik** [comment]
Yes, it works with USDT)  
ty, @jegerima
