### ISSUE TITLE
My bot get a bad hatbit to buy high sell low.....

### ISSUE THREAD

**Issue by e1001925** [ccxt/binance-trade-bot#321]
I don't know why, but it seems my bot recently get a seriously bad habit to buy high and sell at a lower price. Can anyone kindly explain, under what circumstances, the bot will make such a decision?

And I observed that normally the price will recover(some bit) if just wait longer......

**Comment by rel-s** [comment]
Hi, the bot's purpose is not to maximize gains against USD, but rather to increase coin amounts. This can result in a loss of $$$. Please see the README and consult our Discord channel for more information.
