### ISSUE TITLE
i am scouting the best trades

### ISSUE THREAD

**Issue by yemrekula0748** [ccxt/binance-trade-bot#327]
[binance_user_config]
api_key=******
api_secret_key=******
current_coin=WIN
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=2
scout_sleep_time=0
strategy=default
buy_timeout=0
sell_timeout=0

The writing is constantly coming out like this and the program continues to wait. 

i am scouting the best trades current coin wınusdt

**Comment by rel-s** [comment]
This repo uses Issues to track bugs and have meaningful discussions. Please move personal setup problems and questions to our Discord channel.
