### ISSUE TITLE
update coins without deleting old cache

### ISSUE THREAD

**Issue by abanchev** [ccxt/binance-trade-bot#33]
update_trade_threshold should loop through supported_coin_list instead of the current coin_table
this way if we add any coins to the list (and restart the script) it will take them into account after at least one trade is completed

of course care should be taken that the current or next coin is not removed from the list

**Comment by thiazzz** [comment]
Good idea!

**Comment by cobosfernando** [comment]
Also, the .current_coin_table file should be delete if script starts again, isnt it? 
So we will get the new values for coins and that will solve this issue, but anyways better to do the loop over supported_coin_list

**Comment by rel-s** [comment]
`.current_coin_table` should not be deleted when you restart the script - it holds your ratio against every coin in the list, and deleting it may cause the bot to issue "losing" trades. It's a good idea to allow dynamic changing of the supported coin list, and probably will be implemented in the future - maybe through Telegram?

**Comment by j-waters** [comment]
This has been implemented by #93, so can be closed
