### ISSUE TITLE
Apprise Discord notifications not working

### ISSUE THREAD

**Issue by peterwroot** [ccxt/binance-trade-bot#335]
I'm having issues getting the Discord notifications to work. I have done the following:

- Configured a Discord channel and created a webhook
- Added the webhook details into config/apprise.xml
- Stopped and re-started the program and waited for a trade to be conducted. 

Once the trade completed, no message appeared in the discord channel.

Screenshot of my apprise.xml below, with the webhook details blanked out. 

![apprise](https://user-images.githubusercontent.com/39913947/118267134-7cbf7580-b4b3-11eb-805d-aeaeb3e6edd9.PNG)

Apologies if I've not raised this correctly - I've never raised an issue before so I have no idea what I'm doing.

**Comment by peterwroot** [comment]
Another note - I've checked the logs and I can't see anything in there about sending the apprise messages, it just seems to contain the same text that gets outputted to the console.

**Comment by rel-s** [comment]
Hi, many users in this community use apprise successfully to send notifications. The issues of this Github project are not meant for technical support, but rather for bugs with the bot. For help and support, please move this discussion to our Discord channel, and if you do find a bug that causes this open a new issue for it. Thanks!
