### ISSUE TITLE
Suggestions "Profit Percentage"

### ISSUE THREAD

**Issue by MohammedDarwish-0** [ccxt/binance-trade-bot#337]
In the beginning, I would like to thank each developer who participated in the development of this script, and for developing it further, I have two suggestions:
1- What if we were able to determine the daily profit percentage that we want, for example, if we made the bot trade at $1000 and we want a daily profit of only 10% by applying the suggestion that I proposed now, we can put in the "user.cfg" file the profit rate of 10% and upon arrival, It converts automatically to BUSD, for example, and is not traded at all.

2- There is a possibility in the script to determine the percentage of profit from each trade, meaning that sometimes the script remains to wait a lot until it reaches the best selling point, but there is always a safe point that it is good to sell at it and let it be 2% of the amount traded, and the example below will explain More:
For example, I am trading $1000, then the script will trade as follows:
He buys a $1000 DOGE coin at a price of 0.48 cents, which means that I will have approximately 2083 DOGE coins. I only want to gain 5% on the total capital, meaning the script sells when it reaches 0,50 cents, and when it enters the next currency also does so, and by linking this suggestion With the previous suggestion, the script will convert the $50 into the BUSD and trade the $1000 in another currency and convert the profit to the bridge currency, which is not approached unless I convert them to the main bridge currency, for example, the USDT.

**Comment by rel-s** [comment]
Hi, this seems like a rather big change that conflicts with our philosophy. Please move this discussion to the Discord channel, as the issues here are meant for bug reports and relevant discussions.
