### ISSUE TITLE
seems like the total usdt traded is getting smaller and smaller

### ISSUE THREAD

**Issue by eloqven** [ccxt/binance-trade-bot#34]
Am I the only one who sees a problem here?
Sorry if issue is duplicate.
I am just curious about those breadcrumbs.

![image](https://user-images.githubusercontent.com/47355430/107369336-540d9580-6aea-11eb-8577-2fe1169fd24c.png)

**Comment by eloqven** [comment]
well, nevermind
seems like the crumbs aggregate themselves in the end.

but the longer the supported_coin_list, the crumbier the current trade.
because the chance of retrading the same currency decreases.
please correct me if I am wrong...


**
![image](https://user-images.githubusercontent.com/47355430/107374417-3cd1a680-6af0-11eb-8353-cf834b66e6c0.png)
**

**Comment by edeng23** [comment]
Hey, the reason for the crumbs is the "step size" which is defined for every coin. You can't just make an order at any precision, you have to work in multiples of the step size that are greater than the minimum order value.

**Comment by eloqven** [comment]
thanks for clarifying
sorry for the issue.

Tbh it worked pretty nice. I let it run all day and I tweaked the parameters a little bit: removed some crypto from the list and raised the multiplier from 5 to 6 and here are the results: using 100$

**Comment by eloqven** [comment]
![image](https://user-images.githubusercontent.com/47355430/107429078-2d704e80-6b2c-11eb-892b-b793f27137ec.png)

**Comment by eloqven** [comment]
so thank you. the multiplier to 6 helped remove the amount errors from logs.

**Comment by 3xtazzy** [comment]
> thanks for clarifying
> sorry for the issue.
> 
> Tbh it worked pretty nice. I let it run all day and I tweaked the parameters a little bit: removed some crypto from the list and raised the multiplier from 5 to 6 and here are the results: using 100$

Can you share the list? I’m really new to trading

**Comment by eloqven** [comment]
i update the list every day, get the small prices with big volume
>20.000.000

supported_coin_list = [u'XLM', u'TRX', u'EOS', u'ADA', u'XMR', u'VET',
u'XRP', u'SXP', u'IOTA', u'IOST', u'REEF', u'ONT', u'MATIC']
