### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by LorenzHW** [ccxt/binance-trade-bot#343]
Hi,

could you please make a release? That would be appreciated.

**Comment by LorenzHW** [comment]
@rel-s Any specific reason why you closed this issue?

**Comment by rel-s** [comment]
Yep, sorry for not writing an explanation, forgot about it...
We are planning on making a release eventually, but there are a lot of significant changes incoming and it doesn't make much sense in our opinion to make a release before these changes (that should greatly increase bot stability). Thanks for your contributions though!
