### ISSUE TITLE
How to use CFG file

### ISSUE THREAD

**Issue by hamdan-Deb** [ccxt/binance-trade-bot#345]
Can you please guide me about how can I trade ETH and how BOT checks whether I am going to earn profit based of the crypto market activity by Whales.

Can you  please also guide me About the cfg file like what is buy/sell timeouts, what is current coin symbol. Does supported coins  include ETH/USDT... and what is scout thing and its best approach... Thanks

**Comment by MasaiasuOse** [comment]
The bot uses only coins set in the `supported_coin_list`. If you write ETH in it, the bot can use it. The bot calcualtes the ratio between the coin value of the current coin and an optinal coin. Is the ratio positive the bot jumps to that coin.
In the read.me are your answers to your question with the user.cfg:
The configuration file consists of the following fields:

> api_key - Binance API key generated in the Binance account setup stage.
> api_secret_key - Binance secret key generated in the Binance account setup stage.
> current_coin - This is your starting coin of choice. This should be one of the coins from your supported coin list. If you want to start from your bridge currency, leave this field empty - the bot will select a random coin from your supported coin list and buy it.
> bridge - Your bridge currency of choice. Notice that different bridges will allow different sets of supported coins. For example, there may be a Binance particular-coin/USDT pair but no particular-coin/BUSD pair.
> tld - 'com' or 'us', depending on your region. Default is 'com'.
> hourToKeepScoutHistory - Controls how many hours of scouting values are kept in the database. After the amount of time specified has passed, the information will be deleted.
> scout_multiplier - Controls the value by which the difference between the current state of coin ratios and previous state of ratios is multiplied. For bigger values, the bot will wait for bigger margins to arrive before making a trade.
> strategy - The trading strategy to use. See binance_trade_bot/strategies for more information
> buy_timeout/sell_timeout - Controls how many minutes to wait before cancelling a limit order (buy/sell) and returning to "scout" mode. 0 means that the order will never be cancelled prematurely.

**Comment by hamdan-Deb** [comment]
Thanks for your kind response. Really appreciate it.

Can you please guide me how to make bot not to buy more than 10 USDT and
 which settings would be best in cfg file regarding scout strategy and what if I add ETH in supported coins list, the bot would be able to trade profitably ETH in this fluctuating market... and

**Comment by hamdan-Deb** [comment]
Can you please help me on the image beLow :

![thanks](https://user-images.githubusercontent.com/59921920/119599353-bd38c080-bddc-11eb-8b68-a0cb5eada52f.PNG)

**Comment by rel-s** [comment]
The github issues are not a support forum, please move this discussion to our Discord channel.
