### ISSUE TITLE
Is this bug or intended? selling same amount of coin with lower USDT

### ISSUE THREAD

**Issue by chchia** [ccxt/binance-trade-bot#351]
first time user, i just notice it executed a trade that although i keep same amount of coin by with lower USDT

![image](https://user-images.githubusercontent.com/1291771/119707283-925a7500-be8d-11eb-9391-e2e9394d04bc.png)

![image](https://user-images.githubusercontent.com/1291771/119707482-c5046d80-be8d-11eb-8627-32459df89031.png)

**Comment by rel-s** [comment]
Please see the readme for information on how the bot is supposed to function, and for more questions consult our discord channel. Thanks!

**Comment by blacklightpy** [comment]
The bot doesn't seem to care about USD conversion values, but only about increasing the amount of a certain coin. In this case, USDT is a bridge, and it is probably trying to increase the amount of BTT by switching to another coin and eventually getting back to BTT.
