### ISSUE TITLE
crypto_trading_logger - INFO - Starting binance_trader    | Traceback (most recent call last): binance_trader    |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main

### ISSUE THREAD

**Issue by fof-github** [ccxt/binance-trade-bot#353]
Hello,
I got the fork and trying to run the code with docker, after the docker pull edeng23/binance-trade-bot then docker-compose up. 
I'm getting these errors:
[error.pdf](https://github.com/edeng23/binance-trade-bot/files/6556136/error.pdf)

user.cfg file:
api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
api_secret_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
current_coin=
bridge=USDT
tld=binance.com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=60
strategy=default
buy_timeout=0
sell_timeout=0

I could not create user.cfg file in the main directory because there's a folder called user.cfg/ . So i placed it in another folder.

I need some help to get run the bot.
Thank you

**Comment by rel-s** [comment]
This is not a bug. For support, please consult our discord channel.
