### ISSUE TITLE
Binance Testnet API

### ISSUE THREAD

**Issue by cryptacid** [ccxt/binance-trade-bot#362]
There is Binance testnet API:
https://testnet.binance.vision

Is it possible to connect bot with test-net? 
I didn't find any information and tried to just use test-net api keys – no luck.
Thanks.

LOG:
```
2021-06-05 21:55:12,905 - crypto_trading_logger - INFO - Starting
2021-06-05 21:55:13,691 - crypto_trading_logger - ERROR - Couldn't access Binance API - API keys may be wrong or lack sufficient permissions
2021-06-05 21:55:13,691 - crypto_trading_logger - ERROR - APIError(code=-2015): Invalid API-key, IP, or permissions for action.
```

And here are test-net API permissions:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/81503637/120906461-284a8880-c662-11eb-9abd-0d46065e9258.png">

**Comment by Amraki** [comment]
@cryptacid 
From my experience, the testnet server is very limited and has unreliable data. The coin selection is very small and to top it off, the prices aren't in sync with the live market by a large margin.

To test the bot without risking your own money first, check out backtest.py available with the bot version you're using:
[https://github.com/edeng23/binance-trade-bot#backtesting](https://github.com/edeng23/binance-trade-bot#backtesting)
[https://github.com/idkravitz/binance-trade-bot#backtesting](https://github.com/idkravitz/binance-trade-bot#backtesting)

idkravitz is updated more frequently and has nice features in the works.
