### ISSUE TITLE
[question] Can I add as many coin as I wanted?

### ISSUE THREAD

**Issue by phytonnewbe** [ccxt/binance-trade-bot#368]
Hello, 

firstly, thank you for this great tool. 

Can I have around 60 coin in the supported coin list?

Will there be any side effect or something?

**Comment by belentorrente** [comment]
I am using some 25 coins now, and I see the downside of the bot trading too much. I don't know, maybe increasing the threshold before trading could fix this. My instance will sometimes trade every 10 minutes, eventually the  transaction costs are higher than the extra value gained by trading.

**Comment by phytonnewbe** [comment]
That's weird. Because I configured the top 60 (by Market cap) coins and my bot trades 2-3 times only per day. It should be because of the volatility of coins that you have chosen.

**Comment by edeng23** [comment]
Yes, you should be able to add as many coins as you want as long as the pair with the bridge coin exists. The side effect is the increased risk.
