### ISSUE TITLE
Error installing Dep 

### ISSUE THREAD

**Issue by princetigr** [ccxt/binance-trade-bot#37]
Anyone managed to run this on Mac OS?
I am getting below error:

`ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-4r84o1lb/twisted_f26a68bf0dac4915a457aa54e4911bdf/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-4r84o1lb/twisted_f26a68bf0dac4915a457aa54e4911bdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-js45t0wc/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Python/3.8/include/Twisted Check the logs for full command output.`

**Comment by rel-s** [comment]
Please move this discussion to the discord channel, if it's still relevant.
