### ISSUE TITLE
Config file not being used

### ISSUE THREAD

**Issue by belentorrente** [ccxt/binance-trade-bot#374]
I cloned the repo today (June 13), and followed the instructions on the README. This is the content of my config file:

```
SUPPORTED_COIN_LIST: "BNB"
api_key=  MY_KEY
api_secret_key= MY_SECRET_KEY
current_coin=
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_multiplier=5
scout_sleep_time=1
strategy=default
buy_timeout=0
sell_timeout=0
```
I was expecting to try this out with BNB, but the bot has just traded DOGE for ICX. It looks like it's using the `multiple_coins` strategy. However, the logs indicate `crypto_trading_logger - INFO - Chosen strategy: default` when starting the bot. 

Am I doing something wrong, or is this a bug?

**Comment by phytonnewbe** [comment]
There is a seperate file for supported coin list, "supported_coin_list" in the root. You need to modify it accordingly and remove the SUPPORTED_COIN_LIST: "BNB" key from user.cofig. Make sure that you don't have the "crypto_trading.db" under the data folder. If there is any, delete it. Once you run the bot, it should create the db as per your supported count list.

**Comment by belentorrente** [comment]
Yes, I've updated the `supported_coin_list` file, I still don't understand why the default strategy still uses several coins, but the multiple coin strategy works fine.
