### ISSUE TITLE
Ticker does not exist

### ISSUE THREAD

**Issue by belentorrente** [ccxt/binance-trade-bot#375]
When starting the bot, I get the following info messages:

```
crypto_trading_logger - INFO - Ticker does not exist: USDTUSDT - will not be fetched from now on
crypto_trading_logger - INFO - Ticker does not exist: USDTBTC - will not be fetched from now on

```
I understand `UDSTUDST` does not exist, but what about `USDTBTC`? Would this mean that BTC is being discarded as an option?

**Comment by phytonnewbe** [comment]
I also receive such messages and I just ignored them. The bot is running and making some trades. I did not earn anything though but I don't think this message has an  influence.

**Comment by belentorrente** [comment]
Thanks for your reply! Yes, I've noticed that adding a different list of supported coins, more of these messages appear, but the bot is indeed trading.

**Comment by ghost** [comment]
Ticker does not exist: - will not be fetched from now on.
Can you help me regarding this logger?

**Comment by cgermanb** [comment]
I have the same error message, I checked in binance and there is no operation, it remains and does not advance

**Comment by cgermanb** [comment]
Before that message it tells me:
 ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/usr/local/lib/python3.8/site-packages/werkzeug/serving.py)
