### ISSUE TITLE
What is the time interval the bot checks the prices?

### ISSUE THREAD

**Issue by thiazzz** [ccxt/binance-trade-bot#39]
Maybe stupid question, but I can't read the py script so well.
What is the time interval the bot checks the prices?
Can I just leave it running in the terminal?

**Comment by xjakubo** [comment]
bot checks prices only when buying/selling (correct me if I am wrong?) Just add 30 minutes timer to refresh if none actions have taken place. 
add this to start of script:

`updatetime = int(time.time())`

add this to at end of scout()
```
    try:
         if (time.time() - updatetime) > 900:
             update_trade_threshold(client)
             print('updated coin table after 15 minutes!')
             updatetime = int(time.time())
     except:
         print('Cannot update after 15 minutes!')
         time.sleep(5)
```


and voila, coin table refreshes after 15 minutes!
to avoid any errors you can restart updatetime in transaction_through_tether function
I can make pull request with that feature, I edited script from few days ago to resolve some issues.

**Comment by abanchev** [comment]
The cached prices are stored until the next transaction as they are necessary to know what is the threshold that is profitable.
Prices are checked every couple of seconds in the scouting function, but the new prices are not stored, just compared to the threshold to see if a trade should be made. This proposed coin refresh will break the logic of the bot, and lose you money.

**Comment by thiazzz** [comment]
Sounds logical. I see trades happening now. And I see that the amount of the coin are going up. So that seems to work.
