### ISSUE TITLE
Why the bot doesn't sell all the coins but leaves the rest

### ISSUE THREAD

**Issue by Ivvanek** [ccxt/binance-trade-bot#398]
Hi,

I have figured that bot doesn't sell all coins which had bought and leave some rest of coins which cannot been traded.
Any solution?

**Comment by ElektronikerDev** [comment]
The reason is that Binance cannot transfer small amounts at some point. So there is no forgotten amount, but only a remaining amount. 
You can convert residual amounts to BNB in the "Spot overview".

You can then convert BNB into another currency at a certain amount and it's back in the cycle.

**Comment by Ivvanek** [comment]
Yeah, but why the bot doesn't sell ALL amount of coin, just a 99% of coins ? some rest coins still cannot be traded.
Please someone explain me that strategy because i do not understand :D

**Comment by edeng23** [comment]
The trade amount on Binance is calculated in multiplications of the minimal increment. Anything in-between gets left behind.
