### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by thiazzz** [ccxt/binance-trade-bot#40]
I added a telegram bot to the script as I'm running it from a container from my nas. 

It this interesting to submit as new functionality? I've not coded py before so i don't think the code is the best but i got it working in an hour or so. 

Via telegram BotFather there are instructions to create a bot where messages are sent.

https://github.com/thiazzz/binance-trade-bot/commit/efcfed1831f91c7adf855be9605cea01621f057f

https://github.com/thiazzz/binance-trade-bot/commit/37df6cd21d84955837f2adb5974e65f2f03f988a

**Comment by edeng23** [comment]
Hey, I really like this idea! 
Definitely think that this should be submitted as a new functionality. The thing is, I would prefer if the feature was optional and not obligating. Moreover, the more standard way to have both logs happen (logfile and telegram bot) is to add a handler function to the logger. This can be done as seen here:
https://www.marcodena.it/blog/telegram-logging-handler-for-python-java-bash/

**Comment by thiazzz** [comment]
Ok pullrequest created
