### ISSUE TITLE
Telegram Notification not working 

### ISSUE THREAD

**Issue by theogibet** [ccxt/binance-trade-bot#414]
Hey ! 

I have configure Apprise as follow :

```
# Define version
version: 1
- tgram://token/chat_id

urls:
  - tgram://token/chat_id
```

I tested my telegram bot with a curl request, the bot is working and is sending the message in the conversation but it seems like it is not working with the binance bot.

Have I done the config correctly ? 

Have someone  already have the issue ?

Thanks

**Comment by erencelik** [comment]
You should provide your url only below urls: tag and try appending "/" to the end like this;

```
# Define version
version: 1

urls:
  - tgram://token/chat_id/
```

**Comment by theogibet** [comment]
Thanks it works ! As it was written to define the link I thought I needed to double write the urls
