### ISSUE TITLE
how to install docker file

### ISSUE THREAD

**Issue by rwijnhov** [ccxt/binance-trade-bot#415]
Hi do you have any assistance on how to install the docker image and the configuration?

**Comment by raschmitt** [comment]
Actually, a docker image is not installed but run.

Here is the [official docker documentation]( https://docs.docker.com/language/nodejs/run-containers/
) on how to do it.

Yet, for the sake of simplicity, I would strongly suggest that you run this application using `docker-composer` as sugested in the [docker section](https://github.com/edeng23/binance-trade-bot#docker) of the docs.
