### ISSUE TITLE
Add artificial intelligence

### ISSUE THREAD

**Issue by luizpaulonievola** [ccxt/binance-trade-bot#440]
Hi, I found the project interesting, I thought about LSTM or another algorithm as a strategy, would it be interesting?

**Comment by AlbertoSinigaglia** [comment]
worth reading https://www.blueskycapitalmanagement.com/machine-learning-in-finance-why-you-should-not-use-lstms-to-predict-the-stock-market/

**Comment by AlbertoSinigaglia** [comment]
you might probably can, but which factor are you going to take in account? consider that Musk can increase and decrease Doge by 70% in a hour, so you also would have to create a (eg) Twitter scraper on the influencers and so on... probably JPMorgan is doing this, but with a bigger budget

**Comment by maledicente** [comment]
NPL for twitter hehe
