### ISSUE TITLE
After the order is cancelled

### ISSUE THREAD

**Issue by feichenchina** [ccxt/binance-trade-bot#445]
Dear friend, thanks for your project, I find it very interesting!
When the set transaction time is reached, the transaction pair is still not successful, and the program is in an endless loop after the transaction is withdrawn

**Comment by pioardi** [comment]
Thanks for the project, I may have a similar issue my order get stuck for long time  ( couple of hourse ) I was not expecting that, is it the expected behavior ?

**Comment by rel-s** [comment]
Orders can get stuck, nothing to do about it. The bot tries to recover. For questions please consult the discord channel and not github issues.
