### ISSUE TITLE
APIError(code=-2014)

### ISSUE THREAD

**Issue by pereirasantana** [ccxt/binance-trade-bot#448]
When I run "python -m binance_trade_bot" I get the print error, the API works in another python bot with no problems and I'm from outside the US so tld=com. What could be done? Thanks
![erro_bot2](https://user-images.githubusercontent.com/55887140/143483914-de0a2e78-a8b2-48a4-9582-4d6a61af610f.png)
![erro_bot](https://user-images.githubusercontent.com/55887140/143483937-ef563759-f8a4-44fe-9d52-b15cc4d2a003.png)

**Comment by Drjacky** [comment]
This happens when you have not checked all the necessary API restrictions. To be sure about this, just enable all (except the withdrawal) and you'll see it work.

**Comment by MasaiasuOse** [comment]
> This happens when you have not checked all the necessary API restrictions. To be sure about this, just enable all (except the withdrawal) and you'll see it work.

That's wrong. The nessary restrictions are reading and Spot & Margin Trading. Probably something else. Could be that in the coin list are leverage tokens but the guide about leverage tokens wasn't completed yet

**Comment by rel-s** [comment]
This is not an issue with the bot. For technical problems, please consult with the Discord channel.
