### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rhysmarsh** [ccxt/binance-trade-bot#449]
This may not be an issue but rather a path / setup error on my end but in case others may have a similar issue posting my exit error here when running pip install -r requirements.txt after pulling the repository into my root folder.

I'd be most grateful if anyone can point me in the right direction here. 

ERROR: Command errored out with exit status 1:                                                                           command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_h2jacus/pathlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_h2jacus/pathlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_h2jacus/pathlib/pip-egg-info                                                               cwd: /tmp/pip-install-_h2jacus/pathlib/                                                                            Complete output (39 lines):                                                                                             running egg_info                                                                                                        creating /tmp/pip-install-_h2jacus/pathlib/pip-egg-info/pathlib.egg-info                                                writing /tmp/pip-install-_h2jacus/pathlib/pip-egg-info/pathlib.egg-info/PKG-INFO                                        writing dependency_links to /tmp/pip-install-_h2jacus/pathlib/pip-egg-info/pathlib.egg-info/dependency_links.txt        writing top-level names to /tmp/pip-install-_h2jacus/pathlib/pip-egg-info/pathlib.egg-info/top_level.txt                writing manifest file '/tmp/pip-install-_h2jacus/pathlib/pip-egg-info/pathlib.egg-info/SOURCES.txt'                     Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "/tmp/pip-install-_h2jacus/pathlib/setup.py", line 6, in <module>                                                    setup(                                                                                                                File "/usr/lib/python3.8/distutils/core.py", line 148, in setup                                                           dist.run_commands()                                                                                                   File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands                                                    self.run_command(cmd)                                                                                                 File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command                                                     cmd_obj.run()                                                                                                         File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run                                    self.find_sources()                                                                                                   File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources                           mm.run()                                                                                                              File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run                                    self.add_defaults()                                                                                                   File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 575, in add_defaults                           rcfiles = list(walk_revctrl())                                                                                        File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 20, in walk_revctrl                               for item in ep.load()(dirname):                                                                                       File "/home/rhys/.local/lib/python3.8/site-packages/setuptools_scm/integration.py", line 69, in find_files                for ep in iter_entry_points("setuptools_scm.files_command"):                                                          File "/home/rhys/.local/lib/python3.8/site-packages/setuptools_scm/utils.py", line 147, in iter_entry_points              all_eps = entry_points()                                                                                              File "/usr/lib/python3.8/importlib/metadata.py", line 541, in entry_points                                                ordered = sorted(eps, key=by_group)                                                                                   File "/usr/lib/python3.8/importlib/metadata.py", line 539, in <genexpr>                                                   dist.entry_points for dist in distributions())                                                                        File "/usr/lib/python3.8/importlib/metadata.py", line 240, in entry_points                                                return EntryPoint._from_text(self.read_text('entry_points.txt'))                                                      File "/usr/lib/python3.8/importlib/metadata.py", line 490, in read_text                                                   return self._path.joinpath(filename).read_text(encoding='utf-8')                                                    AttributeError: 'PosixPath' object has no attribute 'read_text'                                                         ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Jerjer3333333** [comment]
- [ ]

**Comment by SolosoftNL** [comment]
Hi. It took me also some time and trial and error to getting success. I've also discover these issues. Ultimately I made a clean fresh new install. Which python version do you use?

**Comment by rhysmarsh** [comment]
> Hi. It took me also some time and trial and error to getting success. I've also discover these issues. Ultimately I made a clean fresh new install. Which python version do you use?

I'm using Python 3.8.10

Thanks so much for your reply, will attempt a fresh install & see if that gets me any further

**Comment by Jerjer3333333** [comment]
Would i like to help me get this up and running agian
