### ISSUE TITLE
Changed supported_coins_list, how ReInit Database Scheme?

### ISSUE THREAD

**Issue by SolosoftNL** [ccxt/binance-trade-bot#456]
Hi, i've changed my file: supported_coin_list and removed a coin from the list, but when starting the program it still telling:

INFO - Creating database schema if it doesn't already exist
INFO - I am scouting the best trades. Current coin: REMOVED_COIN

So, how can i reinnitialize the Database scheme? Or do i need te remove the old database? And how to do that?

**Comment by MasaiasuOse** [comment]
The best is to not remove the coin the bot is holding 😉

**Comment by Leoningel** [comment]
I have a similar issue: I want to change the current coin at initialization. When I do that, the coin is chosen from the Db, being the last coin held. Can I change this at initialization? I could also just buy the coin again, but would rather have a more general solution.

**Comment by rel-s** [comment]
For technical issues, please consult the discord channel and not the Github issues...
