### ISSUE TITLE
ERROR: unicorn-binance-websocket-api 1.30.0 has requirement websockets==8.1, but you'll have websockets 10.1 which is incompatible.

### ISSUE THREAD

**Issue by JavaRockstar** [ccxt/binance-trade-bot#457]
ERROR: unicorn-binance-websocket-api 1.30.0 has requirement websockets==8.1, but you'll have websockets 10.1 which is incompatible.

Getting this error when running requirements.txt in Ubuntu

**Comment by craigjr** [comment]
Did you ever figure out how to resolve this error?

**Comment by KYKKIS2** [comment]
yes just uninstall websockets 10.1 and install websockets 8.1, but i think right now it requires 10.0 so just install websockets 10.0 and you are fine.
