### ISSUE TITLE
APIError(code=-2015): Invalid API-key, IP, or permissions for action.

### ISSUE THREAD

**Issue by marcynn** [ccxt/binance-trade-bot#459]
Hello, 

I am getting APIError code=-2015  whenever I create an order on spot trading using either create_test_order or create_order.

I tried the following to no avail:

- I am not specifying "tld" param in the client given that I am not using Binance US.
- I enabled Spot & Margin Trading from API settings.
- I restricted the API key to a trusted IP.

Would appreciate your help , thanks a ton

![image](https://user-images.githubusercontent.com/85497151/147388113-3b0fc7f4-43a6-4a11-ac15-5734518509e3.png)

OS: Linux Mint
Python 3.9.7

**Comment by rel-s** [comment]
Hi, this does not seem to be a bug with the bot. Please consider asking this in the Discord channel.
