### ISSUE TITLE
Re-create Order if Price Shoots Up

### ISSUE THREAD

**Issue by remriel** [ccxt/binance-trade-bot#46]
Is it possible to cancel an order and recreate it at a new price if the price shoots up past the buy limit? 

For example, a buy order is placed for $1 a coin but the price instantly shoots to $1.20 when the order is placed. It will attempt to place the order over and over but fail until the price drops back down.

Instead, can it cancel the order after a certain number of attempts and place a new one for the new price? Or switch to another coin if that's not possible?

**Comment by remriel** [comment]
![image](https://user-images.githubusercontent.com/2818715/107834469-19eefe80-6d4b-11eb-8a1a-2c4ad4d3af11.png)

**Comment by abanchev** [comment]
The new price may not be profitable for you, if you still want to force the trade you can switch to market orders in the code.

**Comment by remriel** [comment]
That works, thank you

**Comment by thiazzz** [comment]
Maybe we could automatically remove the open order if it is not filled within a certain time (like 10 mins). 
The open order will block the USDT funds, also preventing automatic new trades.

**Comment by 3xtazzy** [comment]
> That works, thank you

How?

**Comment by remriel** [comment]
Change
```
            order = client.order_limit_buy(
                symbol=alt_symbol + crypto_symbol,
                quantity=order_quantity,
                price=get_market_ticker_price(client, alt_symbol+crypto_symbol)
```
to
```
            order = client.order_market_buy(
                symbol=alt_symbol + crypto_symbol,
                quantity=order_quantity,
                #price=get_market_ticker_price(client, alt_symbol+crypto_symbol)
```
