### ISSUE TITLE
Errors when trying to run bot

### ISSUE THREAD

**Issue by arigatoexpress** [ccxt/binance-trade-bot#465]
![binance bot](https://user-images.githubusercontent.com/95630102/148802753-015b5d69-f096-464a-bb75-648df507eb8d.PNG)
Hey guys, coding n00b here looking for help running the bot. When I run "python -m binance_trade_bot" I get the following errors (check screenshot)- I am doing this in VScode and would love some help as I'm very much stuck right now!

**Comment by rel-s** [comment]
Please consult the discord channel for technical help.
