### ISSUE TITLE
APIError(code=-1022): Signature for this request is not valid

### ISSUE THREAD

**Issue by HerrmannHinz** [ccxt/binance-trade-bot#47]
hi there,

i searched the issues and the code already but could not find an answer, also did some googling and found out about a param called: `recvWindow` 

and checked this page but i dont know your code too little: https://dev.binance.vision/t/faq-signature-for-this-request-is-not-valid/176

logs: 
``` 
➜  binance-trade-bot git:(master) ✗ ./crypto_trading.py
Failed to Buy/Sell. Trying Again.

2021-02-13 13:22:56,426 - crypto_trader_logger - INFO - Will be jumping from DOGE to TRX
2021-02-13 13:22:58,062 - crypto_trader_logger - INFO - APIError(code=-1022): Signature for this request is not valid.
```

also my API key is not IP limited. 

any idea? 😅

**Comment by HerrmannHinz** [comment]
update: 

introducing the `recvWindow` did not solve it. 

```
RECV_WINDOW=59999

def get_currency_balance(client, currency_symbol):
    '''
    Get balance of a specific coin
    '''
    for currency_balance in client.get_account(recvWindow=RECV_WINDOW)[u'balances']:
        if currency_balance[u'asset'] == currency_symbol:
            return float(currency_balance[u'free'])
    return None
```

**Comment by rel-s** [comment]
Signing and actually passing data on to Binance is done through `python-binance`, which uses your secret key to sign messages. Are you sure your key is entered correctly? Did you manage to successfully use it with another service perhaps?

**Comment by HerrmannHinz** [comment]
> Signing and actually passing data on to Binance is done through `python-binance`, which uses your secret key to sign messages. Are you sure your key is entered correctly? Did you manage to successfully use it with another service perhaps?

actually i did not try it with another service. but worth a try. 
i may generate a new pair of api keys and will try again. but usually i deal a lot on a daily base with keys and key secrets. and i know how to copy paste those. but who knows 😅

thanks! will try again and leave feedback if it works (or not).

**Comment by HerrmannHinz** [comment]
> Signing and actually passing data on to Binance is done through `python-binance`, which uses your secret key to sign messages. Are you sure your key is entered correctly? Did you manage to successfully use it with another service perhaps?

works now after regenerating an api key. thx @rel-s
