### ISSUE TITLE
Error While Scouting Temporary failure in name resolution

### ISSUE THREAD

**Issue by GrzegorzKarczewski** [ccxt/binance-trade-bot#49]
Could this be possible because of connection issues?

2021-02-13 17:21:26,438 - crypto_trader_logger - INFO - Bought XLM
2021-02-13 17:48:42,678 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

2021-02-13 17:49:37,978 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

2021-02-13 17:52:12,911 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

2021-02-13 17:52:29,209 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f56e2ff10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

2021-02-13 17:56:10,362 - crypto_trader_logger - INFO - Error while scouting...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)

**Comment by ivanyyw** [comment]
Did you set the correct DNS server on your server/pc?
Try do ping test "api.binance.com" and see whether you get resolved into IP address.

**Comment by GrzegorzKarczewski** [comment]
Yeah, ping works fine.
/edit. 
Happened three times already, i've put a ping into the api.binance.com into the background to see if there is some connectivity issues on my side. I rerun program with some prints in the main while loop to inform me that there is scouting going on and printed some simple counter.
Will the program sell the last bought coin while price is greater than before ?
Sorry for the offtopic a bit but i'm hardly an expert in python and there isnt a proper chat here

**Comment by rel-s** [comment]
Doesn't sound like a bug in the bot, but rather a setup problem. Please move this discussion to our Discord chat (link in README) if it's still relevant.

**Comment by SonOfCrypto** [comment]
happens to me too. did you find a solution @GrzegorzKarczewski ?
