### ISSUE TITLE
API connection

### ISSUE THREAD

**Issue by B-Mbengue** [ccxt/binance-trade-bot#491]
Hello ; 
When I run the program, I receive these errors :

"Couldn't access Binance API - API keys may be wrong or lack sufficient permissions"
"APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time"

Here the API settings in Binance
![Capture d’écran (33)](https://user-images.githubusercontent.com/59731281/162587105-04cfc7a1-c577-4cd1-a28c-b502fcb578db.jpg)

**Comment by Axelfoley85** [comment]
Just to make sure. Did you properly follow the [instructions to create user configuration](https://github.com/edeng23/binance-trade-bot/blob/master/.user.cfg.example)?

**Comment by MasaiasuOse** [comment]
Make sure that the machine time is synced with a NTP server

**Comment by B-Mbengue** [comment]
It's working now after several trials. I had done these configurations. May be there is a delay before it's fully working particulrary for the sync with a NPT server. 
Thanks
