### ISSUE TITLE
Change bridge coin from USDT to BUSD?

### ISSUE THREAD

**Issue by MarshCarbs** [ccxt/binance-trade-bot#493]
Hey all,
wouldn't it be usefull to replace the bridge coin from USDT to BUSD? 

I mean, they are both stable coins, but the advantage with BUSD would be the increase of the VIP level on binance.

Or is there any disadvantage i am missing?

Greets

**Comment by Axelfoley85** [comment]
You can set your bridge coin in the config file, Just make sure its available on Binance.

**Comment by Axelfoley85** [comment]
Is your issue answered @MarshCarbs?

**Comment by MarshCarbs** [comment]
yes

**Comment by Axelfoley85** [comment]
@MarshCarbs Please you close this issue. Thanks!
