### ISSUE TITLE
APIError(code=-2015)

### ISSUE THREAD

**Issue by ghost** [ccxt/binance-trade-bot#50]
2021-02-13 10:55:03,901 - crypto_trader_logger - INFO - APIError(code=-2015): Invalid API-key, IP, or permissions for action.

I believe this is because I am using a Binance.US api key? 
Is it possible to get it to work with Binance.US also?

**Comment by craigwheeler** [comment]
Whenever you initialize the Client try passing in the tld parameter. 

`client = Client(api_key, api_secret_key, tld='us')`

**Comment by ghost** [comment]
Can you help me a little more and tell me how to do that?
I tried to add tld='us' to line 347 in the crypto_trading.py and get another error. 
Thank you for your time.

**Comment by nrgapple** [comment]
Currently the line is on `368` for me.

```python
client = Client(api_key, api_secret_key, tld='us')
```

I get the same error as before...

I am also using a US key

**Comment by nrgapple** [comment]
Does Advanced Verification and/or Cash Account Verification need to be completed in your binance.us account?

**Comment by ABTDoug** [comment]
> Whenever you initialize the Client try passing in the tld parameter.
> 
> `client = Client(api_key, api_secret_key, tld='us')`

This worked for me, I'm a new Binance user in the US.

**Comment by nrgapple** [comment]
So adding `tld=us` will work **IF** you have already initialized all the coins and the cache folder is created. If you start with the `tld=us` the coins initializing step at the beginning will fail

```
2021-02-17 19:15:42,614 - crypto_trader_logger - INFO - Initializing NEO vs TRX
Traceback (most recent call last):
  File "./crypto_trading.py", line 387, in <module>
    main()
  File "./crypto_trading.py", line 372, in main
    initialize_trade_thresholds(client)
  File "./crypto_trading.py", line 336, in initialize_trade_thresholds
    coin_price = float(get_market_ticker_price(client, coin + 'USDT'))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I think this is because the US version of the coin does not have the `USDT` on the end of it

**Comment by ABTDoug** [comment]
> So adding `tld=us` will work **IF** you have already initialized all the coins and the cache folder is created. If you start with the `tld=us` the coins initializing step at the beginning will fail
> 
> ```
> 2021-02-17 19:15:42,614 - crypto_trader_logger - INFO - Initializing NEO vs TRX
> Traceback (most recent call last):
>   File "./crypto_trading.py", line 387, in <module>
>     main()
>   File "./crypto_trading.py", line 372, in main
>     initialize_trade_thresholds(client)
>   File "./crypto_trading.py", line 336, in initialize_trade_thresholds
>     coin_price = float(get_market_ticker_price(client, coin + 'USDT'))
> TypeError: float() argument must be a string or a number, not 'NoneType'
> ```
> 
> I think this is because the US version of the coin does not have the `USDT` on the end of it

`2021-02-17 16:22:38,542 - crypto_trader_logger - INFO - Started
2021-02-17 16:22:38,542 - crypto_trader_logger - INFO - Setting initial coin to DOGE
2021-02-17 16:22:38,701 - crypto_trader_logger - INFO - Initializing XLM vs XLM
2021-02-17 16:22:38,701 - crypto_trader_logger - INFO - Initializing XLM vs TRX
Traceback (most recent call last):
  File "crypto_trading.py", line 404, in <module>
    main()
  File "crypto_trading.py", line 389, in main
    initialize_trade_thresholds(client)
  File "crypto_trading.py", line 353, in initialize_trade_thresholds
    coin_price = float(get_market_ticker_price(client, coin + 'USD'))
TypeError: float() argument must be a string or a number, not 'NoneType'`

`2021-02-17 16:23:19,330 - crypto_trader_logger - INFO - Started
2021-02-17 16:23:19,331 - crypto_trader_logger - INFO - Setting initial coin to DOGE
2021-02-17 16:23:19,415 - crypto_trader_logger - INFO - Initializing XLM vs XLM
2021-02-17 16:23:19,416 - crypto_trader_logger - INFO - Initializing XLM vs TRX
Traceback (most recent call last):
  File "crypto_trading.py", line 404, in <module>
    main()
  File "crypto_trading.py", line 389, in main
    initialize_trade_thresholds(client)
  File "crypto_trading.py", line 353, in initialize_trade_thresholds
    coin_price = float(get_market_ticker_price(client, coin + 'USDT'))
TypeError: float() argument must be a string or a number, not 'NoneType'`

**Comment by ABTDoug** [comment]
> So adding `tld=us` will work **IF** you have already initialized all the coins and the cache folder is created. If you start with the `tld=us` the coins initializing step at the beginning will fail
> 
> ```
> 2021-02-17 19:15:42,614 - crypto_trader_logger - INFO - Initializing NEO vs TRX
> Traceback (most recent call last):
>   File "./crypto_trading.py", line 387, in <module>
>     main()
>   File "./crypto_trading.py", line 372, in main
>     initialize_trade_thresholds(client)
>   File "./crypto_trading.py", line 336, in initialize_trade_thresholds
>     coin_price = float(get_market_ticker_price(client, coin + 'USDT'))
> TypeError: float() argument must be a string or a number, not 'NoneType'
> ```
> 
> I think this is because the US version of the coin does not have the `USDT` on the end of it

Sorry, I think I posted the wrong output.

I replaced all the USDTs in the file, I get the same result either way.

**Comment by ABTDoug** [comment]
Just to follow up, adding ", tld = 'us'" to the proper line fixed the initialization problem.

Since the US domain doesn't allow all the coins in the supported_coin_list to be traded to/from USDT, I was able to change the supported_coin_list to this list and it stopped throwing anymore errors.

[Different error, but is caused by adding the domain snippit.](https://github.com/edeng23/binance-trade-bot/issues/60#issuecomment-780877676)

**Comment by ghost** [comment]
this is the error i get after adding ", tld = 'us'" to line 368 client = Client(api_key, api_secret_key)

2021-02-17 18:58:30,911 - crypto_trader_logger - INFO - Started
Traceback (most recent call last):
  File "./crypto_trading.py", line 387, in <module>
    main()
  File "./crypto_trading.py", line 368, in main
    client = Client(api_key, api_secret_key, tld = 'us')
TypeError: __init__() got an unexpected keyword argument 'tld'


EDIT: Just saw my account does need advanced verification, have submitted details to have it verified. will update after.

**Comment by edeng23** [comment]
@inhaletime Did you solve this issue?

**Comment by rodrigogs** [comment]
Same problem here

**Comment by ghost** [comment]
@edeng23 no I have not, still waiting for binance.us to do advanced verification if that was needed.

this is the error i get with the latest repo

> python ./crypto_trading.py
> 2021-02-22 17:39:08,232 - crypto_trader_logger - INFO - Started
> Traceback (most recent call last):
>   File "./crypto_trading.py", line 477, in <module>
>     main()
>   File "./crypto_trading.py", line 439, in main
>     client = Client(api_key, api_secret_key, tld=tld)
> TypeError: __init__() got an unexpected keyword argument 'tld'

If i remove tld=tld from the crypto_trading.py i get

> - crypto_trader_logger - INFO - APIError(code=-2015): Invalid API-key, IP, or permissions for action.


my user.cfg

> [binance_user_config]
> api_key=xxxxxxxx
> api_secret_key=xxxxxxxx
> current_coin=ETH
> bridge=USDT
> botChatID=xxxxxxxx
> botToken=xxxxxxxx
> tld=us

**Comment by ghost** [comment]
have edited supported coin list to 
https://github.com/edeng23/binance-trade-bot/issues/60#issuecomment-780877676


same error, have deleted and remade api keys and files. 

> 2021-02-22 18:30:59,169 - crypto_trader_logger - INFO - Started
2021-02-22 18:31:05,027 - crypto_trader_logger - INFO - Will be jumping from <ETH> to <ATOM>
Failed to Buy/Sell. Trying Again.
2021-02-22 18:31:06,445 - crypto_trader_logger - INFO - APIError(code=-2015): Invalid API-key, IP, or permissions for action.
Failed to Buy/Sell. Trying Again.
Failed to Buy/Sell. Trying Again.

**Comment by rel-s** [comment]
Because of recent fixes, US support should now be configurable. Do you still have this problem @inhaletime? It might be because of your Binance API configuration, prohibiting certain actions...

**Comment by inhaletime** [comment]
@rel-s this is the current error it throws with my config. is there something im missing? 

this is my config without my keys.
> [binance_user_config]
> api_key=XXX
> api_secret_key=XXX
> current_coin=ADA
> bridge=USDT
> tld=us
> hourToKeepScoutHistory=1
> scout_transaction_fee=0.001
> scout_multiplier=5
> scout_sleep_time=5



>  python crypto_trading.py
> 2021-02-26 17:09:03,188 - crypto_trader_logger - INFO - Started
> Traceback (most recent call last):
>   File "crypto_trading.py", line 278, in <module>
>     main()
>   File "crypto_trading.py", line 235, in main
>     client = BinanceAPIManager(api_key, api_secret_key, Tld, logger)
>   File "C:\Users\Adobe\Desktop\news\binance-trade-bot-master\binance_api_manager.py", line 11, in __init__
>     self.BinanceClient = Client(APIKey, APISecret, None, Tld)
> TypeError: __init__() takes from 1 to 4 positional arguments but 5 were given

**Comment by ghost** [comment]
Ok, it seems i may of had some outdated python packages, i have updated them and it is now running.  I think the issue has been fixed!

**Comment by rel-s** [comment]
Cheers man
