### ISSUE TITLE
Error while scouting... ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

### ISSUE THREAD

**Issue by darthvader666uk** [ccxt/binance-trade-bot#55]
Hi,

Wondered if you could help.

just updated to the latest Master code and I keep on getting this when kicking off the script.

Any ideas?

**Comment by spectracoin** [comment]
same error here

**Comment by Fernanlonso** [comment]
After 5 hours running without problem (thank you so much for the code, I love it!) I also have the same error.

**Comment by rel-s** [comment]
This doesn't sound like a problem in the bot, but rather a setup problem. Please move this discussion to our Discord chat (link in README) if it's still relevant.

**Comment by chetanc97** [comment]
I think this could be your Internet connection issue or packet loss due to other reasons .
