### ISSUE TITLE
Infinit Loop

### ISSUE THREAD

**Issue by GamerClassN7** [ccxt/binance-trade-bot#58]
sometime i am sucked in infinite loop :(

2021-02-16 11:47:57,415 - crypto_trader_logger - INFO - BUY QTY 0.0
2021-02-16 11:47:59,526 - crypto_trader_logger - INFO - BUY QTY 0.0
2021-02-16 11:48:00,774 - crypto_trader_logger - INFO - BUY QTY 0.0
2021-02-16 11:48:02,015 - crypto_trader_logger - INFO - BUY QTY 0.0

**Comment by slyths** [comment]
I'm not sure, but this might happen if one doesn't have enough crypto to buy the crypto the bot is supposed to buy.
I have had a similar issue, 
Again, i'm not 100% sure.

**Comment by ronnyandre** [comment]
Same issue here.

**Comment by rel-s** [comment]
I suspect, as @slyths wrote, that this may have something to do with a low balance. Can you confirm that your instance is running with a low balance, or is this not the case?

**Comment by ronnyandre** [comment]
@rel-s Define "low balance"? When mine says "Selling 0.0 of ADA" when I currently have 0.97420456 ADA I'm not sure if low balance is the thing?

**Comment by AnasAlmomany** [comment]
Delete 
.current_coin
And .current_coin_table 

Thats should do the trick

**Comment by ronnyandre** [comment]
That's the issue. It doesn't. Currently I'm testing converting all crypto to the same currency and start over.

**Comment by edeng23** [comment]
@ronnyandre Looks like your low balance is causing the problem. Notice that Binance has a minimum trade amount policy.
https://www.binance.com/en/trade-rule
 
<img width="828" alt="Screenshot 2021-02-18 at 20 35 12" src="https://user-images.githubusercontent.com/14821747/108404813-f800ea80-7228-11eb-8723-11e9de00ce7c.png">
