### ISSUE TITLE
Account has insufficient balance for request action

### ISSUE THREAD

**Issue by ronnyandre** [ccxt/binance-trade-bot#62]
I got this error after selling:

    2021-02-16 21:00:23
    APIError(code=-2010): Account has insufficient balance for requested action.

It took a few tries until it bought a new currency, but not sure why this happened?

**Comment by remriel** [comment]
This means the price has changed and the number of coins initially set to be purchased is too expensive. For example, if the order was for 20 coins at $1 each for a total of $20 and the price goes up to $2/coin when the order is placed, the 20 coins now cost $40. 

If you leave it running, it will keep trying to place the order for 20 coins until the price drops to $1 again and the order goes through.

**Comment by ronnyandre** [comment]
Thanks for the explanation.
