### ISSUE TITLE
Trading stops after "Bought "XXX""

### ISSUE THREAD

**Issue by slyths** [ccxt/binance-trade-bot#63]
I have been noticing a strange phenomena with the bot.

It suddenly and randomly stops trading after buying a crypto, the latest was ICX.

It shows no error, or anything, it just sits there with:

`2021-02-17 01:00:42,066 - crypto_trader_logger - INFO - Bought ATOM`
`2021-02-17 01:03:22,017 - crypto_trader_logger - INFO - Will be jumping from ATOM to ICX`
`2021-02-17 01:03:23,529 - crypto_trader_logger - INFO - Selling 3.3 of ATOM`
`2021-02-17 01:03:23,757 - crypto_trader_logger - INFO - Balance is 3.30736`
`2021-02-17 01:03:23,985 - crypto_trader_logger - INFO - order`
`2021-02-17 01:03:23,987 - crypto_trader_logger - INFO - {'symbol': 'ATOMUSDT', 'orderId': 314607984, 'orderListId': -1, 'clientOrderId': 'FlLbzCxm9m1UMBkS2HrXd2', 'transactTime': 1613520203876, 'price': '0.00000000', 'origQty': '3.30000000', 'executedQty': '3.30000000', 'cummulativeQuoteQty': '82.33170000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'fills': [{'price': '24.94900000', 'qty': '3.30000000', 'commission': '0.08233170', 'commissionAsset': 'USDT', 'tradeId': 21429788}]}`
`2021-02-17 01:03:23,989 - crypto_trader_logger - INFO - Waiting for Binance`
`2021-02-17 01:03:32,220 - crypto_trader_logger - INFO - {'symbol': 'ATOMUSDT', 'orderId': 314607984, 'orderListId': -1, 'clientOrderId': 'FlLbzCxm9m1UMBkS2HrXd2', 'price': '0.00000000', 'origQty': '3.30000000', 'executedQty': '3.30000000', 'cummulativeQuoteQty': '82.33170000', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1613520203876, 'updateTime': 1613520203876, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}`
`2021-02-17 01:03:32,463 - crypto_trader_logger - INFO - Sold ATOM`
`2021-02-17 01:03:36,841 - crypto_trader_logger - INFO - BUY QTY 48.3`
`2021-02-17 01:03:37,305 - crypto_trader_logger - INFO - {'symbol': 'ICXUSDT', 'orderId': 175101890, 'orderListId': -1, 'clientOrderId': 'I6FrIxUrdykrvTZhzqWVIi', 'transactTime': 1613520217179, 'price': '1.70150000', 'origQty': '48.30000000', 'executedQty': '0.00000000', 'cummulativeQuoteQty': '0.00000000', 'status': 'NEW', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY', 'fills': []}`
`2021-02-17 01:03:42,176 - crypto_trader_logger - INFO - Bought ICX`

In a few occasions it stays like this for hours. It usually trades for the first 15 mins then stops forever.
When I then close it and reopen it, it sits at:
`2021-02-17 01:21:19,827 - crypto_trader_logger - INFO - Started`

Has anyone encountered this issue, if so, how did you go about it?

What i usually do is, delete : ".current_coin_table" and ".current_coin" then it kind of starts again, then stops after around 15 minutes.

**Comment by ivanyyw** [comment]
I think this how the bot works and intended. Mostly you will get multiple trading on initial hours. But the longer you run, the more stable on hopping coins

**Comment by 3xtazzy** [comment]
It happened to me too, so you deleted  ".current_coin_table" and ".current_coin", and then did you sell the coin that the bot bought previously?

**Comment by rbarbazz** [comment]
This is expected, the "Scouting" log entries were removed in 8616da4d301b4afc75170b05e644db6a6292643d.

**Comment by slyths** [comment]
> It happened to me too, so you deleted  ".current_coin_table" and ".current_coin", and then did you sell the coin that the bot bought previously?

I did not sell that coin, i usually just change the initial coin to the current one, then the cycle begins again.

**Comment by slyths** [comment]
> I think this how the bot works and intended. Mostly you will get multiple trading on initial hours. But the longer you run, the more stable on hopping coins

oh ok, thanks

**Comment by slyths** [comment]
> This is expected, the "Scouting" log entries were removed in 8616da4d301b4afc75170b05e644db6a6292643d.

Alright, thanks

**Comment by 3xtazzy** [comment]
> This is expected, the "Scouting" log entries were removed in [8616da4](https://github.com/edeng23/binance-trade-bot/commit/8616da4d301b4afc75170b05e644db6a6292643d).

Oh... really :( I lost some cents because of this, re-add the Scouting log entry pls

**Comment by rel-s** [comment]
As @rbarbazz said, this is intended behaviour. If something is wrong with the bot you should get an error message. If you are still unsure whether the bot is running or not, you can just restart it and get the "started" log message - I would advise against deleting your `.current_coin_table` file.
