### ISSUE TITLE
Current_coin value

### ISSUE THREAD

**Issue by tinchogon34** [ccxt/binance-trade-bot#64]
Hi, sorry for asking this. I tried to find the answer by myself but I couldn't. What should I write in current_coin value in user.cfg?

Thanks.

**Comment by ivanyyw** [comment]
The current coin you holding in your Binance Account

**Comment by tinchogon34** [comment]
> The current coin you holding in your Binance Account

Right, but if I have for example current_coin=ADA, then the bot ran and sold ADA and bought DOT. If I stop and start the bot again, I should change current_coin to DOT or I can leave it in ADA?.

Thanks

**Comment by tinchogon34** [comment]
Ok, so is the starting current_coin which bot will sell, right? I can see that after selling the current_coin value is tracked inside .current_coin file. I don't need to change current_coin value if I stop and start the bot again.

Thanks!

**Comment by TonyStark** [comment]
@ivanyyw 
i have set current_coin=BTC in user.cfg
got this error
```
2021-02-19 23:25:40,970 - crypto_trader_logger - INFO - Started
2021-02-19 23:25:40,970 - crypto_trader_logger - INFO - Setting initial coin to BTC
***
ERROR!
Since there is no backup file, a proper coin name must be provided at init
***
```

**Comment by ivanyyw** [comment]
> @ivanyyw
> i have set current_coin=BTC in user.cfg
> got this error
> 
> ```
> 2021-02-19 23:25:40,970 - crypto_trader_logger - INFO - Started
> 2021-02-19 23:25:40,970 - crypto_trader_logger - INFO - Setting initial coin to BTC
> ***
> ERROR!
> Since there is no backup file, a proper coin name must be provided at init
> ***
> ```

@TonyStark I believe you have missed to add BTC coin.
If you were using latest build. Add BTC coin at supported_coin_list file

**Comment by TonyStark** [comment]
@ivanyyw 
Ok
i have added BTC to supported coin list
and remove current coin file and table to give fresh start
after executing command, it stuck on generating files
```
2021-02-19 23:34:15,938 - crypto_trader_logger - INFO - Initializing BTC vs EOS
2021-02-19 23:34:15,939 - crypto_trader_logger - INFO - Initializing BTC vs IOTA
2021-02-19 23:34:15,939 - crypto_trader_logger - INFO - Initializing BTC vs ICX
2021-02-19 23:34:15,941 - crypto_trader_logger - INFO - Initializing BTC vs XMR
2021-02-19 23:34:15,942 - crypto_trader_logger - INFO - Initializing BTC vs BTC
2021-02-19 23:34:15,942 - crypto_trader_logger - INFO - Done initializing, generating file
```
or should i transfer my all btc to another cryptocurrency?

**Comment by tinchogon34** [comment]
> @ivanyyw
> Ok
> i have added BTC to supported coin list
> and remove current coin file and table to give fresh start
> after executing command, it stuck on generating files
> 
> ```
> 2021-02-19 23:34:15,938 - crypto_trader_logger - INFO - Initializing BTC vs EOS
> 2021-02-19 23:34:15,939 - crypto_trader_logger - INFO - Initializing BTC vs IOTA
> 2021-02-19 23:34:15,939 - crypto_trader_logger - INFO - Initializing BTC vs ICX
> 2021-02-19 23:34:15,941 - crypto_trader_logger - INFO - Initializing BTC vs XMR
> 2021-02-19 23:34:15,942 - crypto_trader_logger - INFO - Initializing BTC vs BTC
> 2021-02-19 23:34:15,942 - crypto_trader_logger - INFO - Done initializing, generating file
> ```
> 
> or should i transfer my all btc to another cryptocurrency?

That's not a stuck. It's working. You won't see logs until it finds a coin to jump to.
