### ISSUE TITLE
Stuck in an infinite "Selling 0.0 of ADA" loop

### ISSUE THREAD

**Issue by ronnyandre** [ccxt/binance-trade-bot#66]
```
2021-02-17 11:55:01
Done initializing, generating file

2021-02-17 11:55:58
Will be jumping from ADA to IOTA

2021-02-17 11:56:00
Selling 0.0 of ADA

2021-02-17 11:56:01
Balance is 0.13020456

2021-02-17 11:56:01
APIError(code=-1013): Invalid quantity.

2021-02-17 11:56:02
Selling 0.0 of ADA

2021-02-17 11:56:02
Balance is 0.13020456
```

After initializing the currencies, the bot is now stuck in a loop where it repeats "Selling 0.0 of ADA" and "Balance is X.XXX".

I restarted the script, then it said the following:

```
2021-02-17 12:04:13
Started

2021-02-17 12:04:20
Will be jumping from ADA to ONT

2021-02-17 12:04:22
Selling 0.0 of ADA

2021-02-17 12:04:23
Balance is 0.13020456

2021-02-17 12:04:23
APIError(code=-1013): Invalid quantity.

2021-02-17 12:04:24
Selling 0.0 of ADA

2021-02-17 12:04:24
Balance is 0.13020456
```

And so it goes. Tried to remove `.current_coin` file, but then it started again after logging this:

```
2021-02-17 12:06:31
Will be jumping from ADA to XLM

2021-02-17 12:06:33
Selling 0.0 of ADA

2021-02-17 12:06:33
Balance is 0.13020456

2021-02-17 12:06:33
APIError(code=-1013): Invalid quantity.

2021-02-17 12:06:34
Selling 0.0 of ADA
```

**Comment by AnasAlmomany** [comment]
Delete 
.current_coin
And .current_coin_table 

Thats should do the trick

**Comment by rel-s** [comment]
@AnasAlmomany If you just started the bot, deleting `.current_coin` and `.current_coin_table` may be ok. Generally, it's a bad idea to delete `.current_coin_table` as it holds your ratios against all supported coins. I'll look further into this bug when I can.

**Comment by ronnyandre** [comment]
As I commented on another duplicate ticket, deleting `.current_coin` and `.current_coin_table` doesn't actually solve the issue, it reappears again.

So now I am trying collecting all crypto to a common currency to start over.

**Comment by darthvader666uk** [comment]
> 
> 
> As I commented on another duplicate ticket, deleting `.current_coin` and `.current_coin_table` doesn't actually solve the issue, it reappears again.
> 
> So now I am trying collecting all crypto to a common currency to start over.

THis has happened to me a few times

basically keep an eye on the last coin you traded.  Remove current_coin and .current_coin_table BUT updated the user.cfg to the last coin too. 

I found doing it that way keeps it in balance sorta thing.

took a fewe goes to figure it out

**Comment by ronnyandre** [comment]
Funny, as we speak, this appeared:

```
2021-02-18 09:45:47,000 - crypto_trader_logger - INFO - Selling 0.0 of XMR
2021-02-18 09:45:47,267 - crypto_trader_logger - INFO - Balance is 6.08e-05
```

Will try your approach @darthvader666uk

**Comment by AnasAlmomany** [comment]
I can reproduce by trading in the account with the bot running , i only suggested to remove the tables as its a blocker. 
Thanks guys for the good work

**Comment by RealPeha** [comment]
@ronnyandre this issue appears because you already have an active ADA sell order and the script doesn't take this into account and thinks you have ADA

**Comment by TECOLOGYxyz** [comment]
I had the bot running for a few hours without problems and then ran into a similar problem with an infinite loop of:

`2021-02-19 15:36:25,215 - crypto_trader_logger - INFO - Selling 0.0 of XMR`
`2021-02-19 15:36:25,496 - crypto_trader_logger - INFO - Balance is 1.63e-05`
`Failed to Buy/Sell. Trying Again.`


Here's what lead to the infinite loop:

`2021-02-19 15:31:22,230 - crypto_trader_logger - INFO - Bought XMR`
`2021-02-19 15:31:27,802 - crypto_trader_logger - INFO - Will be jumping from XMR to DASH`
`2021-02-19 15:31:29,402 - crypto_trader_logger - INFO - Selling 0.0836 of XMR`
`Failed to Buy/Sell. Trying Again.`
`2021-02-19 15:31:39,405 - crypto_trader_logger - INFO - HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)`
`2021-02-19 15:31:40,774 - crypto_trader_logger - INFO - Selling 0.0836 of XMR`
`2021-02-19 15:31:41,065 - crypto_trader_logger - INFO - Balance is 0.0836163`
`2021-02-19 15:31:41,339 - crypto_trader_logger - INFO - order`
`2021-02-19 15:31:41,340 - crypto_trader_logger - INFO - {'symbol': 'XMRUSDT', 'orderId': 427903435, 'orderListId': -1, 'transactTime': 1613745101212, 'price': '0.00000000', 'origQty': '0.08360000', 'executedQty': '0.08360000', 'cummulativeQuoteQty': '22.12111230', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'fills': [{'price': '264.68000000', 'qty': '0.00001000', 'commission': '0.00000265', 'commissionAsset': 'USDT', 'tradeId': 15468303}, {'price': '264.61000000', 'qty': '0.07648000', 'commission': '0.02023737', 'commissionAsset': 'USDT', 'tradeId': 15468304}, {'price': '264.57000000', 'qty': '0.00711000', 'commission': '0.00188109', 'commissionAsset': 'USDT', 'tradeId': 15468305}]}`
`2021-02-19 15:31:41,341 - crypto_trader_logger - INFO - Waiting for Binance`
`2021-02-19 15:31:49,617 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:32:03,323 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:32:16,607 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:32:29,881 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:32:43,162 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:32:56,434 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:33:10,123 - crypto_trader_logger - INFO - APIError(code=-2013): Order does not exist.`
`2021-02-19 15:33:23,399 - crypto_trader_logger - INFO - {'symbol': 'XMRUSDT', 'orderId': 427903435, 'orderListId': -1, 'price': '0.00000000', 'origQty': '0.08360000', 'executedQty': '0.08360000', 'cummulativeQuoteQty': '22.12111230', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1613745101212, 'updateTime': 1613745101212, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}`
`Failed to Buy/Sell. Trying Again.`
`2021-02-19 15:33:34,261 - crypto_trader_logger - INFO - Selling 0.0 of XMR`
`2021-02-19 15:33:34,549 - crypto_trader_logger - INFO - Balance is 1.63e-05`

**Comment by rel-s** [comment]
This was probably solved by fixing the step size - if the bug persists, please open a new issue.
