### ISSUE TITLE
Error while scouting... ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by tinchogon34** [ccxt/binance-trade-bot#68]
After a few hours of running it started throwing this error. I tried restarting but it's the same.

I don't know what to do.

**Comment by ronnyandre** [comment]
I think this will disappear.

**Comment by rel-s** [comment]
This doesn't sound like a bug in the bot but rather a setup problem. Please move this discussion to Discord (link in README) if it's still relevant.
