### ISSUE TITLE
Coin

### ISSUE THREAD

**Issue by lvivua032** [ccxt/binance-trade-bot#7]
***
ERROR!
Since there is no backup file, a proper coin name must be provided at init
***

**Comment by edeng23** [comment]
When running the bot for the first time, you will be asked to enter the trading symbol of the coin you are currently holding. For example, DOGE or OMG. Make sure that you use one of the coins from the supported coin list that is defined in the bot's code.

**Comment by lvivua032** [comment]
Generating new 'config.txt' file.
CDeP4ed8gSggZPp3GdtKH1NiKFojbvFgM8DMJ7PasI0Zm1qYATzR4v5UGFDfLHoC:
oKCWj48XYcOVCznN889YmANhOpaIHWfO0fHIKzToSf4vi9DJ0odQfhOAyLakb9VH:
DOGE:
***
ERROR!
Since there is no backup file, a proper coin name must be provided at init
***
