### ISSUE TITLE
Read timed out error

### ISSUE THREAD

**Issue by traf** [ccxt/binance-trade-bot#74]
My command line has been stuck at a Read timed out error.

![image](https://user-images.githubusercontent.com/1955831/108268883-2d2f0f00-713b-11eb-84d4-b99f9dc693fe.png)

Any ideas?

**Comment by rel-s** [comment]
This can happen when a buy order is not fulfilled. Check your Binance orders to see if that is the case.

**Comment by edeng23** [comment]
@traf Please update if this is in fact the case.

**Comment by traf** [comment]
Will try again soon so I'll try and close this for now. Thanks!
