### ISSUE TITLE
Failed to Buy/Sell.  APIError(code=-1021)

### ISSUE THREAD

**Issue by VossFynn** [ccxt/binance-trade-bot#78]
After the Setup, I've got this Message:
Failed to Buy/Sell. Trying Again.
2021-02-18 11:07:24,989 - crypto_trader_logger - INFO - APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

IDK what to do. I have the API Key and the Secret Key in there, is there anything I miss?

**Comment by VossFynn** [comment]
https://www.binance.com/de/support/faq/360004492232
I've "synced" the Win Time with "ptbtime1.ptb.de" which is the German Atomic Clock and it still shows up the same Error.
Any Suggestions?

**Comment by VossFynn** [comment]
### SOLVED
To just adjust the Time to the Atomic Clock will not sync your System Clock.
You have to go Control Panel -> Date & Clock -> and then sync your System Time.

**Comment by JanMikes** [comment]
Hi @VossFynn just wanted to say thx, as i just run into same issue and thanks to your note i was able to fix it in the same way 😄

**Comment by VossFynn** [comment]
> Hi @VossFynn just wanted to say thx, as i just run into same issue and thanks to your note i was able to fix it in the same way 😄

Thats nice! :)

**Comment by Hakeemmidan** [comment]
For Mac users, try following [this Stack Exchange answer](https://apple.stackexchange.com/a/117865)
It helped with syncing the time of my Mac with `pool.ntp.org`, which got rid of the error
