### ISSUE TITLE
Bot leaves very small amounts of currencies during the exchange.

### ISSUE THREAD

**Issue by fklosowski** [ccxt/binance-trade-bot#8]
Your bot works with no problems so good job but I do not fully understnd why it keeps very small changes of currencies during every exchange.
After a few exchanges carried out with the help of the bot I have small leftovers of every exchanged currency in my wallet.
Those changes are too small to convert and there's no further use of them.
Is it possible to change bot's logic so it uses MAX amount of given currency on exchange?

**Comment by edeng23** [comment]
Indeed, the problem stems from the fact that I floored the order quantity before sending it out. I did this because I wanted to work with integers instead of figuring out what the expected precision is for each coin. Fixing this should be pretty simple, I'll do it as soon as I have time.

**Comment by fklosowski** [comment]
Ok, cool, thank you.

**Comment by 3xtazzy** [comment]
@edeng23 can you fix this issue? Seems like  the bot still leave small amount of coin

**Comment by fklosowski** [comment]
Well, I noticed recently that if you trade ALTs by hand on Binance spot there are also small amounts of coins left in wallet.
I believe that it's just rounding limitation related especially to very cheap altcoins where 1 coin is worth like 0.02 USDT or so.
