### ISSUE TITLE
"APIError(code=-2013): Order does not exist" is not handled

### ISSUE THREAD

**Issue by ichihaifu** [ccxt/binance-trade-bot#9]
Firstly, thanks for the publication. I've used this for couple days while watching over what it does, and it seems to work fairly well to your theory.

But there is a problem:
Sometimes the script gets stuck in loop during `transaction_through_tether()` due to `APIError(code=-2013): Order does not exist`, and leaves the currency in Tether.

I assume it is due to this section:
https://github.com/edeng23/binance-trade-bot/blob/50784347cad488e1a808763193cad96cfd717a81/crypto_trading.py#L116-L120

I've adjusted the section as seen below, as a band-aid fix, but it might be better to have more graceful check for it.
_(Also, I am not completely certain this solves the problem, as it seems to be sporadic)_
```Python
order = None
while order is None:
    order = client.order_limit_buy(
        symbol=alt_symbol + crypto_symbol,
        quantity=order_quantity,
        price=get_market_ticker_price(client, alt_symbol+crypto_symbol)
    )
```

**Comment by edeng23** [comment]
Hey, thanks for letting me know! For some reason this doesn't happen to me, but I guess that under different network circumstances different things could happen. I agree that the error should be handled - will do.
