### ISSUE TITLE
[Suggestion] Cancel the order after a specific time if not filled, reinitialize and buy again

### ISSUE THREAD

**Issue by mmpantazi** [ccxt/binance-trade-bot#90]
As the title says. Sometimes the bot places a order and it might never get filled if the price keeps going up. It would be nice if it will automatically cancel it after like 30 minutes / 1 hour and buy again.

**Comment by diedline** [comment]
You can change the purchase price to 1.1 times the unit price。

**Comment by mmpantazi** [comment]
That fixes the problem but reduces your profits, you buy with +10% at every order.

**Comment by rel-s** [comment]
This is a duplicate issue, you can comment on the original if you have more suggestions.
