### ISSUE TITLE
Connection to api.binance.com timed out

### ISSUE THREAD

**Issue by LebronCurry** [ccxt/binance-trade-bot#98]
![image](https://user-images.githubusercontent.com/48313599/108579873-03a4fc00-7364-11eb-9b8e-b1eda05f672c.png)
![image](https://user-images.githubusercontent.com/48313599/108579902-161f3580-7364-11eb-99b0-6025baa6fb32.png)
Is there a problem with my network?

**Comment by rel-s** [comment]
Yes, and it's completely out of scope as it is clearly not a bug in this project.

**Comment by fragmentedbin** [comment]
try to use vpn, it's work on me
